/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.portal.service.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import static org.smartunit.runtime.SmartAssertions.*;
import com.macro.mall.mapper.PmsProductMapper;
import com.macro.mall.mapper.SmsCouponHistoryMapper;
import com.macro.mall.mapper.SmsCouponMapper;
import com.macro.mall.mapper.SmsCouponProductCategoryRelationMapper;
import com.macro.mall.mapper.SmsCouponProductRelationMapper;
import com.macro.mall.model.PmsProduct;
import com.macro.mall.model.SmsCoupon;
import com.macro.mall.model.SmsCouponHistory;
import com.macro.mall.model.SmsCouponProductCategoryRelation;
import com.macro.mall.model.SmsCouponProductRelation;
import com.macro.mall.model.UmsMember;
import com.macro.mall.portal.dao.SmsCouponHistoryDao;
import com.macro.mall.portal.domain.CartPromotionItem;
import com.macro.mall.portal.domain.SmsCouponHistoryDetail;
import com.macro.mall.portal.service.UmsMemberService;
import com.macro.mall.portal.service.impl.UmsMemberCouponServiceImpl;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Stack;
import java.util.Vector;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class UmsMemberCouponServiceImpl_SSTest extends UmsMemberCouponServiceImpl_SSTest_scaffolding {
// allCoveredLines:[27, 44, 46, 47, 48, 50, 51, 53, 54, 58, 59, 60, 61, 62, 65, 66, 67, 68, 69, 70, 72, 74, 75, 77, 78, 79, 80, 86, 87, 88, 89, 90, 91, 93, 94, 95, 97, 99, 104, 105, 106, 107, 108, 109, 111, 116, 117, 119, 121, 122, 123, 124, 125, 126, 127, 131, 132, 135, 137, 140, 141, 142, 143, 144, 145, 148, 150, 153, 154, 155, 156, 157, 158, 161, 164, 165, 166, 168, 174, 176, 177, 178, 179, 180, 181, 184, 185, 186, 187, 188, 189, 190, 192, 193, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 210, 211, 215, 216, 217, 218, 219, 220, 224, 225, 226, 227, 228, 230, 231, 235, 236, 237, 238, 239, 241, 242]

  @Test(timeout = 4000)
  public void test_add_00()  throws Throwable  {
      //caseID:8c818e30d2fb1fe7134c0b7133ebc655
      //CoveredLines: [27, 44, 46, 47, 48]
      //Input_0_Long: 337L
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      //mock smsCouponMapper0
      SmsCouponMapper smsCouponMapper0 = mock(SmsCouponMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock umsMemberService0
      UmsMemberService umsMemberService0 = mock(UmsMemberService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "memberService", (Object) umsMemberService0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponMapper", (Object) smsCouponMapper0);
      Long long0 = new Long(337L);
      
      //Call method: add
      // Undeclared exception!
      try { 
        umsMemberCouponServiceImpl0.add(long0);
      } catch(Throwable e) {
         verifyException("com.macro.mall.common.exception.Asserts", e);
         assertEquals("com.macro.mall.common.exception.ApiException", e.getClass().getName());
         assertEquals("\u4F18\u60E0\u5238\u4E0D\u5B58\u5728", e.getMessage());
      }
  }

  @Test(timeout = 4000)
  public void test_add_01()  throws Throwable  {
      //caseID:cca287cf7295da37debde42baa03b93d
      //CoveredLines: [27, 44, 46, 47, 50, 51]
      //Input_0_Long: 100L
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      Integer integer0 = new Integer((-2145382389));
      //mock smsCoupon0
      SmsCoupon smsCoupon0 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(integer0).when(smsCoupon0).getCount();
      //mock smsCouponMapper0
      SmsCouponMapper smsCouponMapper0 = mock(SmsCouponMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(smsCoupon0).when(smsCouponMapper0).selectByPrimaryKey(anyLong());
      //mock umsMember0
      UmsMember umsMember0 = mock(UmsMember.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock umsMemberService0
      UmsMemberService umsMemberService0 = mock(UmsMemberService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(umsMember0).when(umsMemberService0).getCurrentMember();
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "memberService", (Object) umsMemberService0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponMapper", (Object) smsCouponMapper0);
      Long long0 = new Long(100L);
      
      //Call method: add
      // Undeclared exception!
      try { 
        umsMemberCouponServiceImpl0.add(long0);
      } catch(Throwable e) {
         verifyException("com.macro.mall.common.exception.Asserts", e);
         assertEquals("com.macro.mall.common.exception.ApiException", e.getClass().getName());
         assertEquals("\u4F18\u60E0\u5238\u5DF2\u7ECF\u9886\u5B8C\u4E86", e.getMessage());
      }
  }

  @Test(timeout = 4000)
  public void test_add_02()  throws Throwable  {
      //caseID:8bcc05175d9e43bcb28591b3471bfea8
      //CoveredLines: [27, 44, 46, 47, 50, 53, 54, 58, 59, 60, 61, 62]
      //Input_0_Long: 4
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      //mock smsCouponHistoryMapper0
      SmsCouponHistoryMapper smsCouponHistoryMapper0 = mock(SmsCouponHistoryMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(289L).when(smsCouponHistoryMapper0).countByExample(any(com.macro.mall.model.SmsCouponHistoryExample.class));
      Integer integer0 = new Integer(4);
      //mock date0
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock smsCoupon0
      SmsCoupon smsCoupon0 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(integer0).when(smsCoupon0).getCount();
      doReturn(date0).when(smsCoupon0).getEnableTime();
      doReturn(integer0).when(smsCoupon0).getPerLimit();
      //mock smsCouponMapper0
      SmsCouponMapper smsCouponMapper0 = mock(SmsCouponMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(smsCoupon0).when(smsCouponMapper0).selectByPrimaryKey(anyLong());
      Long long0 = new Long(4);
      //mock umsMember0
      UmsMember umsMember0 = mock(UmsMember.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(umsMember0).getId();
      //mock umsMemberService0
      UmsMemberService umsMemberService0 = mock(UmsMemberService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(umsMember0).when(umsMemberService0).getCurrentMember();
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "memberService", (Object) umsMemberService0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponMapper", (Object) smsCouponMapper0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponHistoryMapper", (Object) smsCouponHistoryMapper0);
      
      //Call method: add
      // Undeclared exception!
      try { 
        umsMemberCouponServiceImpl0.add(long0);
      } catch(Throwable e) {
         verifyException("com.macro.mall.common.exception.Asserts", e);
         assertEquals("com.macro.mall.common.exception.ApiException", e.getClass().getName());
         assertEquals("\u60A8\u5DF2\u7ECF\u9886\u53D6\u8FC7\u8BE5\u4F18\u60E0\u5238", e.getMessage());
      }
  }

  @Test(timeout = 4000)
  public void test_add_03()  throws Throwable  {
      //caseID:834a69d12e6212281a6c68a7c45d359e
      //CoveredLines: [27, 44, 46, 47, 50, 53, 54, 58, 59, 60, 61, 65, 66, 67, 68, 69, 70, 72, 74, 75, 77, 78, 79, 80, 86, 87, 88, 89, 90, 91, 93, 94, 95, 99]
      //Input_0_Long: 125
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      //mock smsCouponHistoryMapper0
      SmsCouponHistoryMapper smsCouponHistoryMapper0 = mock(SmsCouponHistoryMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn((-2L)).when(smsCouponHistoryMapper0).countByExample(any(com.macro.mall.model.SmsCouponHistoryExample.class));
      doReturn(125).when(smsCouponHistoryMapper0).insert(any(com.macro.mall.model.SmsCouponHistory.class));
      Integer integer0 = new Integer(125);
      //mock date0
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock smsCoupon0
      SmsCoupon smsCoupon0 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(integer0, integer0).when(smsCoupon0).getCount();
      doReturn(date0).when(smsCoupon0).getEnableTime();
      doReturn(integer0).when(smsCoupon0).getPerLimit();
      doReturn(integer0, integer0).when(smsCoupon0).getReceiveCount();
      //mock smsCouponMapper0
      SmsCouponMapper smsCouponMapper0 = mock(SmsCouponMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(smsCoupon0).when(smsCouponMapper0).selectByPrimaryKey(anyLong());
      doReturn(125).when(smsCouponMapper0).updateByPrimaryKey(any(com.macro.mall.model.SmsCoupon.class));
      Long long0 = new Long(125);
      //mock umsMember0
      UmsMember umsMember0 = mock(UmsMember.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0, long0, long0).when(umsMember0).getId();
      doReturn("0").when(umsMember0).getNickname();
      //mock umsMemberService0
      UmsMemberService umsMemberService0 = mock(UmsMemberService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(umsMember0).when(umsMemberService0).getCurrentMember();
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "memberService", (Object) umsMemberService0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponMapper", (Object) smsCouponMapper0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponHistoryMapper", (Object) smsCouponHistoryMapper0);
      
      //Call method: add
      umsMemberCouponServiceImpl0.add(long0);
  }

  @Test(timeout = 4000)
  public void test_add_04()  throws Throwable  {
      //caseID:85c9a19f179cbb8e253540677fadca9e
      //CoveredLines: [27, 44, 46, 47, 50, 53, 54, 58, 59, 60, 61, 65, 66, 67, 68, 69, 70, 72, 74, 75, 77, 78, 79, 80, 86, 87, 88, 89, 90, 91, 93, 94, 97, 99]
      //Input_0_Long: 2142233076
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      //mock smsCouponHistoryMapper0
      SmsCouponHistoryMapper smsCouponHistoryMapper0 = mock(SmsCouponHistoryMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(533L).when(smsCouponHistoryMapper0).countByExample(any(com.macro.mall.model.SmsCouponHistoryExample.class));
      Integer integer0 = new Integer(2142233076);
      //mock date0
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock smsCoupon0
      SmsCoupon smsCoupon0 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(integer0).when(smsCoupon0).getCount();
      doReturn(date0).when(smsCoupon0).getEnableTime();
      doReturn(integer0).when(smsCoupon0).getPerLimit();
      //mock smsCouponMapper0
      SmsCouponMapper smsCouponMapper0 = mock(SmsCouponMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(smsCoupon0).when(smsCouponMapper0).selectByPrimaryKey(anyLong());
      Long long0 = new Long(2142233076);
      //mock umsMember0
      UmsMember umsMember0 = mock(UmsMember.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(umsMember0).getId();
      //mock umsMemberService0
      UmsMemberService umsMemberService0 = mock(UmsMemberService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(umsMember0).when(umsMemberService0).getCurrentMember();
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "memberService", (Object) umsMemberService0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponMapper", (Object) smsCouponMapper0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponHistoryMapper", (Object) smsCouponHistoryMapper0);
      
      //Call method: add
      umsMemberCouponServiceImpl0.add(long0);
  }

  @Test(timeout = 4000)
  public void test_calcTotalAmountByProductId_05()  throws Throwable  {
      //caseID:bc8c616db5954b256b8353ddf6f98313
      //CoveredLines: [27, 235, 236, 237, 241, 242]
      //Input_0_List<com.macro.mall.portal.domain.CartPromotionItem>: vector0
      //Input_1_List<Long>: arrayList0
      //Assert: assertEquals((byte)0, method_result.byteValue());
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      Vector<CartPromotionItem> vector0 = new Vector<CartPromotionItem>();
      Long long0 = new Long(0L);
      //mock cartPromotionItem0
      CartPromotionItem cartPromotionItem0 = mock(CartPromotionItem.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(cartPromotionItem0).getProductId();
      
      vector0.add(cartPromotionItem0);
      ArrayList<Long> arrayList0 = new ArrayList<Long>();
      
      //Call method: calcTotalAmountByProductId
      BigDecimal bigDecimal0 = (BigDecimal)PrivateAccess.callMethod((Class<UmsMemberCouponServiceImpl>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "calcTotalAmountByProductId", (Object) vector0, (Class<?>) List.class, (Object) arrayList0, (Class<?>) List.class);
      
      //Test Result Assert
      assertEquals((byte)0, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test_calcTotalAmountByProductId_06()  throws Throwable  {
      //caseID:c224c2c087cb0a6897ca0f6a0f172d37
      //CoveredLines: [27, 235, 236, 237, 238, 239, 241, 242]
      //Input_0_List<com.macro.mall.portal.domain.CartPromotionItem>: stack0
      //Input_1_List<Long>: vector0
      //Assert: assertSame(method_result, bigDecimal0);
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      Stack<CartPromotionItem> stack0 = new Stack<CartPromotionItem>();
      Long long0 = new Long(0L);
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      Integer integer0 = new Integer((-354));
      //mock cartPromotionItem0
      CartPromotionItem cartPromotionItem0 = mock(CartPromotionItem.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(bigDecimal0).when(cartPromotionItem0).getPrice();
      doReturn(long0).when(cartPromotionItem0).getProductId();
      doReturn(integer0).when(cartPromotionItem0).getQuantity();
      doReturn(bigDecimal0).when(cartPromotionItem0).getReduceAmount();
      
      stack0.add(cartPromotionItem0);
      Vector<Long> vector0 = new Vector<Long>();
      
      vector0.add(long0);
      
      //Call method: calcTotalAmountByProductId
      Object object0 = PrivateAccess.callMethod((Class<UmsMemberCouponServiceImpl>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "calcTotalAmountByProductId", (Object) stack0, (Class<?>) List.class, (Object) vector0, (Class<?>) List.class);
      
      //Test Result Assert
      assertSame(object0, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test_calcTotalAmountByproductCategoryId_07()  throws Throwable  {
      //caseID:3212488a43eeb2a3d34dd7faccf2c072
      //CoveredLines: [27, 224, 225, 226, 230, 231]
      //Input_0_List<com.macro.mall.portal.domain.CartPromotionItem>: linkedList0
      //Input_1_List<Long>: vector0
      //Assert: assertEquals((short)0, method_result.shortValue());
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      LinkedList<CartPromotionItem> linkedList0 = new LinkedList<CartPromotionItem>();
      //mock cartPromotionItem0
      CartPromotionItem cartPromotionItem0 = mock(CartPromotionItem.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      linkedList0.add(cartPromotionItem0);
      Vector<Long> vector0 = new Vector<Long>();
      
      //Call method: calcTotalAmountByproductCategoryId
      BigDecimal bigDecimal0 = (BigDecimal)PrivateAccess.callMethod((Class<UmsMemberCouponServiceImpl>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "calcTotalAmountByproductCategoryId", (Object) linkedList0, (Class<?>) List.class, (Object) vector0, (Class<?>) List.class);
      
      //Test Result Assert
      assertEquals((short)0, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test_calcTotalAmountByproductCategoryId_08()  throws Throwable  {
      //caseID:20a5de8fd7d6c8ba71307d30ccb52dd5
      //CoveredLines: [27, 224, 225, 226, 227, 228, 230, 231]
      //Input_0_List<com.macro.mall.portal.domain.CartPromotionItem>: linkedList0
      //Input_1_List<Long>: arrayList0
      //Assert: assertEquals((short)0, method_result.shortValue());
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      LinkedList<CartPromotionItem> linkedList0 = new LinkedList<CartPromotionItem>();
      Long long0 = new Long(0L);
      BigDecimal bigDecimal0 = new BigDecimal(308.7);
      Integer integer0 = new Integer(10);
      //mock cartPromotionItem0
      CartPromotionItem cartPromotionItem0 = mock(CartPromotionItem.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(bigDecimal0).when(cartPromotionItem0).getPrice();
      doReturn(long0).when(cartPromotionItem0).getProductCategoryId();
      doReturn(integer0).when(cartPromotionItem0).getQuantity();
      doReturn(bigDecimal0).when(cartPromotionItem0).getReduceAmount();
      
      linkedList0.add(cartPromotionItem0);
      ArrayList<Long> arrayList0 = new ArrayList<Long>();
      
      arrayList0.add(long0);
      
      //Call method: calcTotalAmountByproductCategoryId
      BigDecimal bigDecimal1 = (BigDecimal)PrivateAccess.callMethod((Class<UmsMemberCouponServiceImpl>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "calcTotalAmountByproductCategoryId", (Object) linkedList0, (Class<?>) List.class, (Object) arrayList0, (Class<?>) List.class);
      
      //Test Result Assert
      assertEquals((short)0, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test_list_09()  throws Throwable  {
      //caseID:155a6638955f27987a0c4d333b220167
      //CoveredLines: [27, 210, 211]
      //Input_0_Integer: 10
      //Assert: assertNull(method_result);
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      //mock smsCouponHistoryDao0
      SmsCouponHistoryDao smsCouponHistoryDao0 = mock(SmsCouponHistoryDao.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock umsMember0
      UmsMember umsMember0 = mock(UmsMember.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock umsMemberService0
      UmsMemberService umsMemberService0 = mock(UmsMemberService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(umsMember0).when(umsMemberService0).getCurrentMember();
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "memberService", (Object) umsMemberService0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponHistoryDao", (Object) smsCouponHistoryDao0);
      Integer integer0 = new Integer(10);
      
      //Call method: list
      List<SmsCoupon> list0 = umsMemberCouponServiceImpl0.list(integer0);
      
      //Test Result Assert
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test_listByProduct_10()  throws Throwable  {
      //caseID:8fc561fbe9200cc16ea71ce1db38ccec
      //CoveredLines: [27, 174, 176, 177, 178, 179, 184, 185, 186, 187, 188, 192, 193]
      //Input_0_Long: 0L
      //Assert: assertTrue(method_result.isEmpty());
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      Long long0 = new Long(0L);
      //mock pmsProduct0
      PmsProduct pmsProduct0 = mock(PmsProduct.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(pmsProduct0).getProductCategoryId();
      //mock pmsProductMapper0
      PmsProductMapper pmsProductMapper0 = mock(PmsProductMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(pmsProduct0).when(pmsProductMapper0).selectByPrimaryKey(anyLong());
      //mock smsCouponProductCategoryRelationMapper0
      SmsCouponProductCategoryRelationMapper smsCouponProductCategoryRelationMapper0 = mock(SmsCouponProductCategoryRelationMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      Stack<SmsCouponProductRelation> stack0 = new Stack<SmsCouponProductRelation>();
      //mock smsCouponProductRelationMapper0
      SmsCouponProductRelationMapper smsCouponProductRelationMapper0 = mock(SmsCouponProductRelationMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(stack0).when(smsCouponProductRelationMapper0).selectByExample(any(com.macro.mall.model.SmsCouponProductRelationExample.class));
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponProductRelationMapper", (Object) smsCouponProductRelationMapper0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponProductCategoryRelationMapper", (Object) smsCouponProductCategoryRelationMapper0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "productMapper", (Object) pmsProductMapper0);
      
      //Call method: listByProduct
      List<SmsCoupon> list0 = umsMemberCouponServiceImpl0.listByProduct(long0);
      
      //Test Result Assert
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test_listByProduct_11()  throws Throwable  {
      //caseID:63be7374a5a82986ee4ef39fe1a9520e
      //CoveredLines: [27, 174, 176, 177, 178, 179, 184, 185, 186, 187, 188, 189, 190, 192, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205]
      //Input_0_Long: 0L
      //Assert: assertNull(method_result);
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      Long long0 = new Long(0L);
      //mock pmsProduct0
      PmsProduct pmsProduct0 = mock(PmsProduct.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(pmsProduct0).getProductCategoryId();
      //mock pmsProductMapper0
      PmsProductMapper pmsProductMapper0 = mock(PmsProductMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(pmsProduct0).when(pmsProductMapper0).selectByPrimaryKey(anyLong());
      //mock smsCouponMapper0
      SmsCouponMapper smsCouponMapper0 = mock(SmsCouponMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      LinkedList<SmsCouponProductCategoryRelation> linkedList0 = new LinkedList<SmsCouponProductCategoryRelation>();
      //mock smsCouponProductCategoryRelation0
      SmsCouponProductCategoryRelation smsCouponProductCategoryRelation0 = mock(SmsCouponProductCategoryRelation.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      linkedList0.add(smsCouponProductCategoryRelation0);
      //mock smsCouponProductCategoryRelationMapper0
      SmsCouponProductCategoryRelationMapper smsCouponProductCategoryRelationMapper0 = mock(SmsCouponProductCategoryRelationMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(linkedList0).when(smsCouponProductCategoryRelationMapper0).selectByExample(any(com.macro.mall.model.SmsCouponProductCategoryRelationExample.class));
      Stack<SmsCouponProductRelation> stack0 = new Stack<SmsCouponProductRelation>();
      //mock smsCouponProductRelationMapper0
      SmsCouponProductRelationMapper smsCouponProductRelationMapper0 = mock(SmsCouponProductRelationMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(stack0).when(smsCouponProductRelationMapper0).selectByExample(any(com.macro.mall.model.SmsCouponProductRelationExample.class));
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponProductRelationMapper", (Object) smsCouponProductRelationMapper0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponProductCategoryRelationMapper", (Object) smsCouponProductCategoryRelationMapper0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponMapper", (Object) smsCouponMapper0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "productMapper", (Object) pmsProductMapper0);
      
      //Call method: listByProduct
      List<SmsCoupon> list0 = umsMemberCouponServiceImpl0.listByProduct(long0);
      
      //Test Result Assert
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test_listByProduct_12()  throws Throwable  {
      //caseID:396b530f514e0cecea09c0ab72a281e5
      //CoveredLines: [27, 174, 176, 177, 178, 179, 180, 181, 184, 185, 186, 187, 188, 192, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205]
      //Input_0_Long: 0L
      //Assert: assertNull(method_result);
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      Long long0 = new Long(0L);
      //mock pmsProduct0
      PmsProduct pmsProduct0 = mock(PmsProduct.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(pmsProduct0).getProductCategoryId();
      //mock pmsProductMapper0
      PmsProductMapper pmsProductMapper0 = mock(PmsProductMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(pmsProduct0).when(pmsProductMapper0).selectByPrimaryKey(anyLong());
      //mock smsCouponMapper0
      SmsCouponMapper smsCouponMapper0 = mock(SmsCouponMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock smsCouponProductCategoryRelationMapper0
      SmsCouponProductCategoryRelationMapper smsCouponProductCategoryRelationMapper0 = mock(SmsCouponProductCategoryRelationMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      LinkedList<SmsCouponProductRelation> linkedList0 = new LinkedList<SmsCouponProductRelation>();
      //mock smsCouponProductRelation0
      SmsCouponProductRelation smsCouponProductRelation0 = mock(SmsCouponProductRelation.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(smsCouponProductRelation0).getCouponId();
      
      linkedList0.add(smsCouponProductRelation0);
      //mock smsCouponProductRelationMapper0
      SmsCouponProductRelationMapper smsCouponProductRelationMapper0 = mock(SmsCouponProductRelationMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(linkedList0).when(smsCouponProductRelationMapper0).selectByExample(any(com.macro.mall.model.SmsCouponProductRelationExample.class));
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponProductRelationMapper", (Object) smsCouponProductRelationMapper0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponProductCategoryRelationMapper", (Object) smsCouponProductCategoryRelationMapper0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponMapper", (Object) smsCouponMapper0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "productMapper", (Object) pmsProductMapper0);
      
      //Call method: listByProduct
      List<SmsCoupon> list0 = umsMemberCouponServiceImpl0.listByProduct(long0);
      
      //Test Result Assert
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test_listByProduct_13()  throws Throwable  {
      //caseID:24ef5c4ca20d073876990f99ddc33dff
      //CoveredLines: [27, 174, 176, 177, 178, 179, 180, 181, 184, 185, 186, 187, 188, 189, 190, 192, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205]
      //Input_0_Long: 1L
      //Assert: assertEquals(0, method_result.size());
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      Long long0 = new Long(1L);
      //mock pmsProduct0
      PmsProduct pmsProduct0 = mock(PmsProduct.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(pmsProduct0).getProductCategoryId();
      //mock pmsProductMapper0
      PmsProductMapper pmsProductMapper0 = mock(PmsProductMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(pmsProduct0).when(pmsProductMapper0).selectByPrimaryKey(anyLong());
      ArrayList<SmsCoupon> arrayList0 = new ArrayList<SmsCoupon>();
      //mock smsCouponMapper0
      SmsCouponMapper smsCouponMapper0 = mock(SmsCouponMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(arrayList0).when(smsCouponMapper0).selectByExample(any(com.macro.mall.model.SmsCouponExample.class));
      LinkedList<SmsCouponProductCategoryRelation> linkedList0 = new LinkedList<SmsCouponProductCategoryRelation>();
      //mock smsCouponProductCategoryRelation0
      SmsCouponProductCategoryRelation smsCouponProductCategoryRelation0 = mock(SmsCouponProductCategoryRelation.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(smsCouponProductCategoryRelation0).getCouponId();
      
      linkedList0.add(smsCouponProductCategoryRelation0);
      //mock smsCouponProductCategoryRelationMapper0
      SmsCouponProductCategoryRelationMapper smsCouponProductCategoryRelationMapper0 = mock(SmsCouponProductCategoryRelationMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(linkedList0).when(smsCouponProductCategoryRelationMapper0).selectByExample(any(com.macro.mall.model.SmsCouponProductCategoryRelationExample.class));
      ArrayList<SmsCouponProductRelation> arrayList1 = new ArrayList<SmsCouponProductRelation>();
      //mock smsCouponProductRelation0
      SmsCouponProductRelation smsCouponProductRelation0 = mock(SmsCouponProductRelation.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(smsCouponProductRelation0).getCouponId();
      
      arrayList1.add(smsCouponProductRelation0);
      //mock smsCouponProductRelationMapper0
      SmsCouponProductRelationMapper smsCouponProductRelationMapper0 = mock(SmsCouponProductRelationMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(arrayList1).when(smsCouponProductRelationMapper0).selectByExample(any(com.macro.mall.model.SmsCouponProductRelationExample.class));
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponProductRelationMapper", (Object) smsCouponProductRelationMapper0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponProductCategoryRelationMapper", (Object) smsCouponProductCategoryRelationMapper0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponMapper", (Object) smsCouponMapper0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "productMapper", (Object) pmsProductMapper0);
      
      //Call method: listByProduct
      List<SmsCoupon> list0 = umsMemberCouponServiceImpl0.listByProduct(long0);
      
      //Test Result Assert
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test_listCart_14()  throws Throwable  {
      //caseID:43d46f47b65ce265133659397fc1b7bf
      //CoveredLines: [27, 116, 117, 119, 121, 122, 123, 124, 125, 126, 127, 164, 165, 168]
      //Input_0_List<CartPromotionItem>: stack0
      //Input_1_Integer: (-1)
      //Assert: assertFalse(method_result.contains(smsCouponHistoryDetail0));
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      ArrayList<SmsCouponHistoryDetail> arrayList0 = new ArrayList<SmsCouponHistoryDetail>();
      Integer integer0 = new Integer((-1));
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      //mock date0
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock smsCoupon0
      SmsCoupon smsCoupon0 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(integer0).when(smsCoupon0).getUseType();
      //mock smsCoupon1
      SmsCoupon smsCoupon1 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(date0).when(smsCoupon1).getEndTime();
      //mock smsCoupon2
      SmsCoupon smsCoupon2 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(bigDecimal0).when(smsCoupon2).getMinPoint();
      //mock smsCouponHistoryDetail0
      SmsCouponHistoryDetail smsCouponHistoryDetail0 = mock(SmsCouponHistoryDetail.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(smsCoupon0, smsCoupon2, smsCoupon1).when(smsCouponHistoryDetail0).getCoupon();
      
      arrayList0.add(smsCouponHistoryDetail0);
      //mock smsCouponHistoryDao0
      SmsCouponHistoryDao smsCouponHistoryDao0 = mock(SmsCouponHistoryDao.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(arrayList0).when(smsCouponHistoryDao0).getDetailList(nullable(java.lang.Long.class));
      Long long0 = new Long((-1));
      //mock umsMember0
      UmsMember umsMember0 = mock(UmsMember.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(umsMember0).getId();
      //mock umsMemberService0
      UmsMemberService umsMemberService0 = mock(UmsMemberService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(umsMember0).when(umsMemberService0).getCurrentMember();
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "memberService", (Object) umsMemberService0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponHistoryDao", (Object) smsCouponHistoryDao0);
      Stack<CartPromotionItem> stack0 = new Stack<CartPromotionItem>();
      
      //Call method: listCart
      List<SmsCouponHistoryDetail> list0 = umsMemberCouponServiceImpl0.listCart(stack0, integer0);
      
      //Test Result Assert
      assertFalse(list0.contains(smsCouponHistoryDetail0));
  }

  @Test(timeout = 4000)
  public void test_listCart_15()  throws Throwable  {
      //caseID:56b1e4163f03541398e4a51d65f170ca
      //CoveredLines: [27, 116, 117, 119, 121, 122, 123, 124, 125, 126, 127, 153, 154, 155, 156, 157, 158, 161, 164, 165, 168, 235, 236, 242]
      //Input_0_List<CartPromotionItem>: stack0
      //Input_1_Integer: 2
      //Assert: assertEquals(1, method_result.size());
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      ArrayList<SmsCouponHistoryDetail> arrayList0 = new ArrayList<SmsCouponHistoryDetail>();
      Integer integer0 = new Integer(2);
      BigDecimal bigDecimal0 = new BigDecimal(2);
      //mock date0
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock smsCoupon0
      SmsCoupon smsCoupon0 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(integer0).when(smsCoupon0).getUseType();
      //mock smsCoupon1
      SmsCoupon smsCoupon1 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(date0).when(smsCoupon1).getEndTime();
      //mock smsCoupon2
      SmsCoupon smsCoupon2 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(bigDecimal0).when(smsCoupon2).getMinPoint();
      Vector<SmsCouponProductRelation> vector0 = new Vector<SmsCouponProductRelation>();
      //mock smsCouponProductRelation0
      SmsCouponProductRelation smsCouponProductRelation0 = mock(SmsCouponProductRelation.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      vector0.add(smsCouponProductRelation0);
      //mock smsCouponHistoryDetail0
      SmsCouponHistoryDetail smsCouponHistoryDetail0 = mock(SmsCouponHistoryDetail.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(smsCoupon0, smsCoupon2, smsCoupon1).when(smsCouponHistoryDetail0).getCoupon();
      doReturn(vector0).when(smsCouponHistoryDetail0).getProductRelationList();
      
      arrayList0.add(smsCouponHistoryDetail0);
      //mock smsCouponHistoryDao0
      SmsCouponHistoryDao smsCouponHistoryDao0 = mock(SmsCouponHistoryDao.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(arrayList0).when(smsCouponHistoryDao0).getDetailList(nullable(java.lang.Long.class));
      Long long0 = new Long(2);
      //mock umsMember0
      UmsMember umsMember0 = mock(UmsMember.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(umsMember0).getId();
      //mock umsMemberService0
      UmsMemberService umsMemberService0 = mock(UmsMemberService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(umsMember0).when(umsMemberService0).getCurrentMember();
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "memberService", (Object) umsMemberService0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponHistoryDao", (Object) smsCouponHistoryDao0);
      Stack<CartPromotionItem> stack0 = new Stack<CartPromotionItem>();
      
      //Call method: listCart
      List<SmsCouponHistoryDetail> list0 = umsMemberCouponServiceImpl0.listCart(stack0, integer0);
      
      //Test Result Assert
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test_listCart_16()  throws Throwable  {
      //caseID:f30e9418b79e112e0463036deebead18
      //CoveredLines: [27, 116, 117, 119, 121, 122, 123, 124, 125, 126, 127, 131, 132, 135, 137, 164, 165, 168, 215, 216, 217, 218, 219, 220]
      //Input_0_List<CartPromotionItem>: linkedList1
      //Input_1_Integer: 0
      //Assert: assertTrue(method_result.contains(smsCouponHistoryDetail0));
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      LinkedList<SmsCouponHistoryDetail> linkedList0 = new LinkedList<SmsCouponHistoryDetail>();
      Integer integer0 = new Integer(0);
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      //mock date0
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock smsCoupon0
      SmsCoupon smsCoupon0 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(integer0).when(smsCoupon0).getUseType();
      //mock smsCoupon1
      SmsCoupon smsCoupon1 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(date0).when(smsCoupon1).getEndTime();
      //mock smsCoupon2
      SmsCoupon smsCoupon2 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(bigDecimal0).when(smsCoupon2).getMinPoint();
      //mock smsCouponHistoryDetail0
      SmsCouponHistoryDetail smsCouponHistoryDetail0 = mock(SmsCouponHistoryDetail.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(smsCoupon0, smsCoupon2, smsCoupon1).when(smsCouponHistoryDetail0).getCoupon();
      
      linkedList0.add(smsCouponHistoryDetail0);
      //mock smsCouponHistoryDao0
      SmsCouponHistoryDao smsCouponHistoryDao0 = mock(SmsCouponHistoryDao.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(linkedList0).when(smsCouponHistoryDao0).getDetailList(nullable(java.lang.Long.class));
      Long long0 = new Long(0L);
      //mock umsMember0
      UmsMember umsMember0 = mock(UmsMember.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(umsMember0).getId();
      //mock umsMemberService0
      UmsMemberService umsMemberService0 = mock(UmsMemberService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(umsMember0).when(umsMemberService0).getCurrentMember();
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "memberService", (Object) umsMemberService0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponHistoryDao", (Object) smsCouponHistoryDao0);
      LinkedList<CartPromotionItem> linkedList1 = new LinkedList<CartPromotionItem>();
      //mock cartPromotionItem0
      CartPromotionItem cartPromotionItem0 = mock(CartPromotionItem.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(bigDecimal0).when(cartPromotionItem0).getPrice();
      doReturn(integer0).when(cartPromotionItem0).getQuantity();
      doReturn(bigDecimal0).when(cartPromotionItem0).getReduceAmount();
      
      linkedList1.add(cartPromotionItem0);
      
      //Call method: listCart
      List<SmsCouponHistoryDetail> list0 = umsMemberCouponServiceImpl0.listCart(linkedList1, integer0);
      
      //Test Result Assert
      assertTrue(list0.contains(smsCouponHistoryDetail0));
  }

  @Test(timeout = 4000)
  public void test_listCart_17()  throws Throwable  {
      //caseID:eb87ba7ed1919507b6da7757f79938e5
      //CoveredLines: [27, 116, 117, 119, 121, 122, 123, 124, 125, 126, 127, 140, 141, 142, 143, 144, 145, 148, 150, 164, 165, 168, 224, 225, 231]
      //Input_0_List<CartPromotionItem>: stack1
      //Input_1_Integer: 0
      //Assert: assertEquals(1, method_result.size());
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      LinkedList<SmsCouponHistoryDetail> linkedList0 = new LinkedList<SmsCouponHistoryDetail>();
      //mock smsCouponHistoryDao0
      SmsCouponHistoryDao smsCouponHistoryDao0 = mock(SmsCouponHistoryDao.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(linkedList0).when(smsCouponHistoryDao0).getDetailList(nullable(java.lang.Long.class));
      Integer integer0 = new Integer(1);
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      //mock smsCoupon0
      SmsCoupon smsCoupon0 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(integer0).when(smsCoupon0).getUseType();
      //mock date0
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock smsCoupon1
      SmsCoupon smsCoupon1 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(date0).when(smsCoupon1).getEndTime();
      //mock smsCoupon2
      SmsCoupon smsCoupon2 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(bigDecimal0).when(smsCoupon2).getMinPoint();
      Stack<SmsCouponProductCategoryRelation> stack0 = new Stack<SmsCouponProductCategoryRelation>();
      //mock smsCouponProductCategoryRelation0
      SmsCouponProductCategoryRelation smsCouponProductCategoryRelation0 = mock(SmsCouponProductCategoryRelation.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      stack0.add(smsCouponProductCategoryRelation0);
      //mock smsCouponHistoryDetail0
      SmsCouponHistoryDetail smsCouponHistoryDetail0 = mock(SmsCouponHistoryDetail.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(stack0).when(smsCouponHistoryDetail0).getCategoryRelationList();
      doReturn(smsCoupon0, smsCoupon2, smsCoupon1).when(smsCouponHistoryDetail0).getCoupon();
      
      linkedList0.add(smsCouponHistoryDetail0);
      Long long0 = new Long(0L);
      //mock umsMember0
      UmsMember umsMember0 = mock(UmsMember.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(umsMember0).getId();
      //mock umsMemberService0
      UmsMemberService umsMemberService0 = mock(UmsMemberService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(umsMember0).when(umsMemberService0).getCurrentMember();
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "memberService", (Object) umsMemberService0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponHistoryDao", (Object) smsCouponHistoryDao0);
      Stack<CartPromotionItem> stack1 = new Stack<CartPromotionItem>();
      Integer integer1 = new Integer(0);
      
      //Call method: listCart
      List<SmsCouponHistoryDetail> list0 = umsMemberCouponServiceImpl0.listCart(stack1, integer1);
      
      //Test Result Assert
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test_listCart_18()  throws Throwable  {
      //caseID:da02f51fcd9fc6a2450b4793680ddc64
      //CoveredLines: [27, 116, 117, 119, 121, 122, 123, 124, 125, 126, 127, 140, 141, 142, 143, 144, 145, 148, 150, 164, 165, 166, 224, 225, 231]
      //Input_0_List<CartPromotionItem>: stack0
      //Input_1_Integer: 1
      //Assert: assertEquals(0, method_result.size());
      //Assert: assertEquals("[]", stack0.toString());
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      ArrayList<SmsCouponHistoryDetail> arrayList0 = new ArrayList<SmsCouponHistoryDetail>();
      Integer integer0 = new Integer(1);
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      //mock date0
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock smsCoupon0
      SmsCoupon smsCoupon0 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(integer0).when(smsCoupon0).getUseType();
      //mock smsCoupon1
      SmsCoupon smsCoupon1 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(date0).when(smsCoupon1).getEndTime();
      //mock smsCoupon2
      SmsCoupon smsCoupon2 = mock(SmsCoupon.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(bigDecimal0).when(smsCoupon2).getMinPoint();
      ArrayList<SmsCouponProductCategoryRelation> arrayList1 = new ArrayList<SmsCouponProductCategoryRelation>();
      //mock smsCouponProductCategoryRelation0
      SmsCouponProductCategoryRelation smsCouponProductCategoryRelation0 = mock(SmsCouponProductCategoryRelation.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      arrayList1.add(smsCouponProductCategoryRelation0);
      //mock smsCouponHistoryDetail0
      SmsCouponHistoryDetail smsCouponHistoryDetail0 = mock(SmsCouponHistoryDetail.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(arrayList1).when(smsCouponHistoryDetail0).getCategoryRelationList();
      doReturn(smsCoupon0, smsCoupon2, smsCoupon1).when(smsCouponHistoryDetail0).getCoupon();
      
      arrayList0.add(smsCouponHistoryDetail0);
      //mock smsCouponHistoryDao0
      SmsCouponHistoryDao smsCouponHistoryDao0 = mock(SmsCouponHistoryDao.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(arrayList0).when(smsCouponHistoryDao0).getDetailList(nullable(java.lang.Long.class));
      Long long0 = new Long(1);
      //mock umsMember0
      UmsMember umsMember0 = mock(UmsMember.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(umsMember0).getId();
      //mock umsMemberService0
      UmsMemberService umsMemberService0 = mock(UmsMemberService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(umsMember0).when(umsMemberService0).getCurrentMember();
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "memberService", (Object) umsMemberService0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponHistoryDao", (Object) smsCouponHistoryDao0);
      Stack<CartPromotionItem> stack0 = new Stack<CartPromotionItem>();
      
      //Call method: listCart
      List<SmsCouponHistoryDetail> list0 = umsMemberCouponServiceImpl0.listCart(stack0, integer0);
      
      //Test Result Assert
      assertEquals(0, list0.size());
      
      //Test Result Assert
      assertEquals("[]", stack0.toString());
  }

  @Test(timeout = 4000)
  public void test_listHistory_19()  throws Throwable  {
      //caseID:593b984cd530d37fa4988117052f986e
      //CoveredLines: [27, 104, 105, 106, 107, 108, 109, 111]
      //Input_0_Integer: 0
      //Assert: assertNull(method_result);
      
      UmsMemberCouponServiceImpl umsMemberCouponServiceImpl0 = new UmsMemberCouponServiceImpl();
      //mock smsCouponHistoryMapper0
      SmsCouponHistoryMapper smsCouponHistoryMapper0 = mock(SmsCouponHistoryMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      Long long0 = new Long(0L);
      //mock umsMember0
      UmsMember umsMember0 = mock(UmsMember.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0).when(umsMember0).getId();
      //mock umsMemberService0
      UmsMemberService umsMemberService0 = mock(UmsMemberService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(umsMember0).when(umsMemberService0).getCurrentMember();
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "memberService", (Object) umsMemberService0);
      
      PrivateAccess.setVariable((Class<?>) UmsMemberCouponServiceImpl.class, umsMemberCouponServiceImpl0, "couponHistoryMapper", (Object) smsCouponHistoryMapper0);
      Integer integer0 = new Integer(0);
      
      //Call method: listHistory
      List<SmsCouponHistory> list0 = umsMemberCouponServiceImpl0.listHistory(integer0);
      
      //Test Result Assert
      assertNull(list0);
  }
}
