/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.dto.OmsOrderQueryParam;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class OmsOrderQueryParam_SSTest extends OmsOrderQueryParam_SSTest_scaffolding {
// allCoveredLines:[12, 13, 15, 17, 19, 21, 23, 25]

  @Test(timeout = 4000)
  public void test_getCreateTime_00()  throws Throwable  {
      //caseID:4db3c83898be02195a72c52edffc4483
      //CoveredLines: [13, 25]
      //Assert: assertNull(method_result);
      
      OmsOrderQueryParam omsOrderQueryParam0 = new OmsOrderQueryParam();
      
      //Call method: getCreateTime
      String string0 = omsOrderQueryParam0.getCreateTime();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getOrderSn_01()  throws Throwable  {
      //caseID:dd86033aa4638fd6cdbefef0ee280326
      //CoveredLines: [13, 15]
      //Assert: assertNull(method_result);
      
      OmsOrderQueryParam omsOrderQueryParam0 = new OmsOrderQueryParam();
      
      //Call method: getOrderSn
      String string0 = omsOrderQueryParam0.getOrderSn();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getOrderType_02()  throws Throwable  {
      //caseID:8c1060bd41a7a6ab3a321034553eca96
      //CoveredLines: [13, 21]
      //Assert: assertNull(method_result);
      
      OmsOrderQueryParam omsOrderQueryParam0 = new OmsOrderQueryParam();
      
      //Call method: getOrderType
      Integer integer0 = omsOrderQueryParam0.getOrderType();
      
      //Test Result Assert
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test_getReceiverKeyword_03()  throws Throwable  {
      //caseID:0abf13398012ed529edd359201a78b4f
      //CoveredLines: [13, 17]
      //Assert: assertNull(method_result);
      
      OmsOrderQueryParam omsOrderQueryParam0 = new OmsOrderQueryParam();
      
      //Call method: getReceiverKeyword
      String string0 = omsOrderQueryParam0.getReceiverKeyword();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getSourceType_04()  throws Throwable  {
      //caseID:5b348e3681e969ff7e720ca842f172a6
      //CoveredLines: [13, 23]
      //Assert: assertNull(method_result);
      
      OmsOrderQueryParam omsOrderQueryParam0 = new OmsOrderQueryParam();
      
      //Call method: getSourceType
      Integer integer0 = omsOrderQueryParam0.getSourceType();
      
      //Test Result Assert
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test_getStatus_05()  throws Throwable  {
      //caseID:3af695b785049e6bb4aca6660bb4e1ff
      //CoveredLines: [13, 19]
      //Assert: assertNull(method_result);
      
      OmsOrderQueryParam omsOrderQueryParam0 = new OmsOrderQueryParam();
      
      //Call method: getStatus
      Integer integer0 = omsOrderQueryParam0.getStatus();
      
      //Test Result Assert
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test_setCreateTime_06()  throws Throwable  {
      //caseID:3879e1d96cac0396526babbececd78c6
      //CoveredLines: [12, 12, 12, 12, 12, 12, 13]
      //Input_0_String: com.macro.mall.dto.OmsOrderQueryParam
      
      OmsOrderQueryParam omsOrderQueryParam0 = new OmsOrderQueryParam();
      
      //Call method: setCreateTime
      omsOrderQueryParam0.setCreateTime("com.macro.mall.dto.OmsOrderQueryParam");
      
      //Test Result Assert
      assertNull(omsOrderQueryParam0.getOrderSn());
  }

  @Test(timeout = 4000)
  public void test_setOrderSn_07()  throws Throwable  {
      //caseID:745709f8d2812174e01e1f288dd4bb44
      //CoveredLines: [12, 12, 12, 12, 12, 12, 13]
      //Input_0_String: com.macro.mall.dto.OmsOrderQueryParam
      
      OmsOrderQueryParam omsOrderQueryParam0 = new OmsOrderQueryParam();
      
      //Call method: setOrderSn
      omsOrderQueryParam0.setOrderSn("com.macro.mall.dto.OmsOrderQueryParam");
      
      //Test Result Assert
      assertNull(omsOrderQueryParam0.getSourceType());
  }

  @Test(timeout = 4000)
  public void test_setOrderType_08()  throws Throwable  {
      //caseID:90767e9c8345eed03f9e15f66b1de4ab
      //CoveredLines: [12, 12, 12, 12, 12, 12, 13]
      //Input_0_Integer: (-12)
      
      OmsOrderQueryParam omsOrderQueryParam0 = new OmsOrderQueryParam();
      Integer integer0 = new Integer((-12));
      
      //Call method: setOrderType
      omsOrderQueryParam0.setOrderType(integer0);
      
      //Test Result Assert
      assertNull(omsOrderQueryParam0.getOrderSn());
  }

  @Test(timeout = 4000)
  public void test_setReceiverKeyword_09()  throws Throwable  {
      //caseID:df8e5969508a44669c26f12944e0f30b
      //CoveredLines: [12, 12, 12, 12, 12, 12, 13]
      //Input_0_String: 
      
      OmsOrderQueryParam omsOrderQueryParam0 = new OmsOrderQueryParam();
      
      //Call method: setReceiverKeyword
      omsOrderQueryParam0.setReceiverKeyword("");
      
      //Test Result Assert
      assertEquals("", omsOrderQueryParam0.getReceiverKeyword());
  }

  @Test(timeout = 4000)
  public void test_setSourceType_10()  throws Throwable  {
      //caseID:87506dff8377398950afa43e40194a96
      //CoveredLines: [12, 12, 12, 12, 12, 12, 13]
      //Input_0_Integer: 1330
      
      OmsOrderQueryParam omsOrderQueryParam0 = new OmsOrderQueryParam();
      Integer integer0 = new Integer(1330);
      
      //Call method: setSourceType
      omsOrderQueryParam0.setSourceType(integer0);
      
      //Test Result Assert
      assertNull(omsOrderQueryParam0.getReceiverKeyword());
  }

  @Test(timeout = 4000)
  public void test_setStatus_11()  throws Throwable  {
      //caseID:970b2e42ab77ec79fe730b86173b31d4
      //CoveredLines: [12, 12, 12, 12, 12, 12, 13]
      //Input_0_Integer: 1
      
      OmsOrderQueryParam omsOrderQueryParam0 = new OmsOrderQueryParam();
      Integer integer0 = new Integer(1);
      
      //Call method: setStatus
      omsOrderQueryParam0.setStatus(integer0);
      
      //Test Result Assert
      assertNull(omsOrderQueryParam0.getOrderSn());
  }
}
