/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.dto.PmsProductParam;
import com.macro.mall.model.CmsPrefrenceAreaProductRelation;
import com.macro.mall.model.CmsSubjectProductRelation;
import com.macro.mall.model.PmsMemberPrice;
import com.macro.mall.model.PmsProductAttributeValue;
import com.macro.mall.model.PmsProductFullReduction;
import com.macro.mall.model.PmsProductLadder;
import com.macro.mall.model.PmsSkuStock;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Stack;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class PmsProductParam_SSTest extends PmsProductParam_SSTest_scaffolding {
// allCoveredLines:[14, 15, 18, 20, 22, 24, 26, 28, 30]

  @Test(timeout = 4000)
  public void test_equals_00()  throws Throwable  {
      //caseID:255b236bbc8528eb20885c8248e3d147
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15]
      //Input_0_Object: stack0
      //Assert: assertFalse(method_result);
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      Stack<CmsSubjectProductRelation> stack0 = new Stack<CmsSubjectProductRelation>();
      
      //Call method: equals
      boolean boolean0 = pmsProductParam0.equals(stack0);
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_01()  throws Throwable  {
      //caseID:cdce8268f0ac89f36416d3ccbd9d4e73
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15]
      //Input_0_Object: pmsProductParam0
      //Assert: assertTrue(method_result);
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      
      //Call method: equals
      boolean boolean0 = pmsProductParam0.equals(pmsProductParam0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_02()  throws Throwable  {
      //caseID:3ebe8e4cbad0a84d9cc58adb984a9e0c
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 18, 20, 22, 24, 26, 28, 30]
      //Input_0_Object: pmsProductParam1
      //Assert: assertTrue(method_result);
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      PmsProductParam pmsProductParam1 = new PmsProductParam();
      
      //Call method: equals
      boolean boolean0 = pmsProductParam0.equals(pmsProductParam1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test_hashCode_03()  throws Throwable  {
      //caseID:bac4cb2983eec2471d07bdb1d60dd616
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 18, 20, 22, 24, 26, 28, 30]
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      
      //Call method: hashCode
      pmsProductParam0.hashCode();
  }

  @Test(timeout = 4000)
  public void test_setMemberPriceList_04()  throws Throwable  {
      //caseID:1c587f1669ae372137740c6b0908b328
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_List<PmsMemberPrice>: stack0
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      Stack<PmsMemberPrice> stack0 = new Stack<PmsMemberPrice>();
      
      //Call method: setMemberPriceList
      pmsProductParam0.setMemberPriceList(stack0);
      
      //Test Result Assert
      assertNull(pmsProductParam0.getDeleteStatus());
  }

  @Test(timeout = 4000)
  public void test_setPrefrenceAreaProductRelationList_05()  throws Throwable  {
      //caseID:bfa3627f21f955ee1c349e57e94d38f3
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_List<CmsPrefrenceAreaProductRelation>: linkedList0
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      LinkedList<CmsPrefrenceAreaProductRelation> linkedList0 = new LinkedList<CmsPrefrenceAreaProductRelation>();
      
      //Call method: setPrefrenceAreaProductRelationList
      pmsProductParam0.setPrefrenceAreaProductRelationList(linkedList0);
      
      //Test Result Assert
      assertNull(pmsProductParam0.getServiceIds());
  }

  @Test(timeout = 4000)
  public void test_setProductAttributeValueList_06()  throws Throwable  {
      //caseID:72156b65454196a915a48dd1d85c567b
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_List<PmsProductAttributeValue>: stack0
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      Stack<PmsProductAttributeValue> stack0 = new Stack<PmsProductAttributeValue>();
      
      //Call method: setProductAttributeValueList
      pmsProductParam0.setProductAttributeValueList(stack0);
      
      //Test Result Assert
      assertNull(pmsProductParam0.getDeleteStatus());
  }

  @Test(timeout = 4000)
  public void test_setProductFullReductionList_07()  throws Throwable  {
      //caseID:94606673383bfd86742c19600010e734
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_List<PmsProductFullReduction>: linkedList0
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      LinkedList<PmsProductFullReduction> linkedList0 = new LinkedList<PmsProductFullReduction>();
      
      //Call method: setProductFullReductionList
      pmsProductParam0.setProductFullReductionList(linkedList0);
      
      //Test Result Assert
      assertNull(pmsProductParam0.getUnit());
  }

  @Test(timeout = 4000)
  public void test_setProductLadderList_08()  throws Throwable  {
      //caseID:9d89d549e04d49094e1538a4126dfab7
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_List<PmsProductLadder>: linkedList0
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      LinkedList<PmsProductLadder> linkedList0 = new LinkedList<PmsProductLadder>();
      
      //Call method: setProductLadderList
      pmsProductParam0.setProductLadderList(linkedList0);
      
      //Test Result Assert
      assertNull(pmsProductParam0.getBrandId());
  }

  @Test(timeout = 4000)
  public void test_setSkuStockList_09()  throws Throwable  {
      //caseID:a10499e8ca6657a2eff69bf40e5a4230
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_List<PmsSkuStock>: arrayList0
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      ArrayList<PmsSkuStock> arrayList0 = new ArrayList<PmsSkuStock>();
      
      //Call method: setSkuStockList
      pmsProductParam0.setSkuStockList(arrayList0);
      
      //Test Result Assert
      assertNull(pmsProductParam0.getProductCategoryId());
  }

  @Test(timeout = 4000)
  public void test_setSubjectProductRelationList_10()  throws Throwable  {
      //caseID:ca7e1902663a19712f6159a60a092b5c
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_List<CmsSubjectProductRelation>: arrayList0
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      ArrayList<CmsSubjectProductRelation> arrayList0 = new ArrayList<CmsSubjectProductRelation>();
      
      //Call method: setSubjectProductRelationList
      pmsProductParam0.setSubjectProductRelationList(arrayList0);
      
      //Test Result Assert
      assertNull(pmsProductParam0.getLowStock());
  }

  @Test(timeout = 4000)
  public void test_toString_11()  throws Throwable  {
      //caseID:6cd80d8f65aebd060829281c99f806be
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14, 18, 20, 22, 24, 26, 28, 30]
      //Assert: assertEquals("PmsProductParam(productLadderList=null, productFullReductionList=null, memberPriceList=null, skuStockList=null, productAttributeValueList=null, subjectProductRelationList=null, prefrenceAreaProductRelationList=null)", method_result);
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      
      //Call method: toString
      String string0 = pmsProductParam0.toString();
      
      //Test Result Assert
      assertEquals("PmsProductParam(productLadderList=null, productFullReductionList=null, memberPriceList=null, skuStockList=null, productAttributeValueList=null, subjectProductRelationList=null, prefrenceAreaProductRelationList=null)", string0);
  }
}
