/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.dto.PmsProductParam;
import com.macro.mall.model.CmsPrefrenceAreaProductRelation;
import com.macro.mall.model.CmsSubjectProductRelation;
import com.macro.mall.model.PmsMemberPrice;
import com.macro.mall.model.PmsProductAttributeValue;
import com.macro.mall.model.PmsProductFullReduction;
import com.macro.mall.model.PmsProductLadder;
import com.macro.mall.model.PmsSkuStock;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import org.junit.runner.RunWith;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class PmsProductParam_SSTest extends PmsProductParam_SSTest_scaffolding {
// allCoveredLines:[14, 15, 18, 20, 22, 24, 26, 28, 30]

  @Test(timeout = 4000)
  public void test_canEqual_00()  throws Throwable  {
      //caseID:58a0b4d3dd47064f7189a305623ec2dd
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15]
      //Input_0_Object: , subjectProductRelationList=
      //Assert: assertFalse(method_result);
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      
      //Call method: canEqual
      boolean boolean0 = (boolean)PrivateAccess.callMethod((Class<PmsProductParam>) PmsProductParam.class, pmsProductParam0, "canEqual", (Object) ", subjectProductRelationList=", (Class<?>) Object.class);
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_01()  throws Throwable  {
      //caseID:3e1f2bd98c3b62208fbe5e3cf9e4d5da
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15]
      //Input_0_Object: pmsProductParam0
      //Assert: assertTrue(method_result);
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      
      //Call method: equals
      boolean boolean0 = pmsProductParam0.equals(pmsProductParam0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_02()  throws Throwable  {
      //caseID:510846ef8a679919a5457424eb3111a4
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15]
      //Input_0_Object: linkedList0
      //Assert: assertFalse(method_result);
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      LinkedList<CmsPrefrenceAreaProductRelation> linkedList0 = new LinkedList<CmsPrefrenceAreaProductRelation>();
      
      //Call method: equals
      boolean boolean0 = pmsProductParam0.equals(linkedList0);
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test_hashCode_03()  throws Throwable  {
      //caseID:d775b6eee416bb86a001f81e2339c07e
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 18, 20, 22, 24, 26, 28, 30]
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      
      //Call method: hashCode
      pmsProductParam0.hashCode();
  }

  @Test(timeout = 4000)
  public void test_setMemberPriceList_04()  throws Throwable  {
      //caseID:a46ce47385a3724eb5b5f664aaab3eb7
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_List<PmsMemberPrice>: linkedList0
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      LinkedList<PmsMemberPrice> linkedList0 = new LinkedList<PmsMemberPrice>();
      
      //Call method: setMemberPriceList
      pmsProductParam0.setMemberPriceList(linkedList0);
      
      //Test Result Assert
      assertNull(pmsProductParam0.getFeightTemplateId());
  }

  @Test(timeout = 4000)
  public void test_setPrefrenceAreaProductRelationList_05()  throws Throwable  {
      //caseID:85c2bb5d372ce234405c5ca005298be8
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_List<CmsPrefrenceAreaProductRelation>: vector0
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      Vector<CmsPrefrenceAreaProductRelation> vector0 = new Vector<CmsPrefrenceAreaProductRelation>();
      
      //Call method: setPrefrenceAreaProductRelationList
      pmsProductParam0.setPrefrenceAreaProductRelationList(vector0);
      
      //Test Result Assert
      assertNull(pmsProductParam0.getKeywords());
  }

  @Test(timeout = 4000)
  public void test_setProductAttributeValueList_06()  throws Throwable  {
      //caseID:9c16fdb3418808a1ddafc706d61f442c
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_List<PmsProductAttributeValue>: linkedList0
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      LinkedList<PmsProductAttributeValue> linkedList0 = new LinkedList<PmsProductAttributeValue>();
      
      //Call method: setProductAttributeValueList
      pmsProductParam0.setProductAttributeValueList(linkedList0);
      
      //Test Result Assert
      assertNull(pmsProductParam0.getProductCategoryId());
  }

  @Test(timeout = 4000)
  public void test_setProductFullReductionList_07()  throws Throwable  {
      //caseID:86a705ea020334a218af095fc5d40ff9
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_List<PmsProductFullReduction>: vector0
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      Vector<PmsProductFullReduction> vector0 = new Vector<PmsProductFullReduction>();
      
      //Call method: setProductFullReductionList
      pmsProductParam0.setProductFullReductionList(vector0);
      
      //Test Result Assert
      assertEquals("[]", vector0.toString());
  }

  @Test(timeout = 4000)
  public void test_setProductLadderList_08()  throws Throwable  {
      //caseID:b2f0168dd4438073690a8ea6ccf92dcf
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_List<PmsProductLadder>: vector0
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      Vector<PmsProductLadder> vector0 = new Vector<PmsProductLadder>();
      
      //Call method: setProductLadderList
      pmsProductParam0.setProductLadderList(vector0);
      
      //Test Result Assert
      assertNull(pmsProductParam0.getBrandName());
  }

  @Test(timeout = 4000)
  public void test_setSkuStockList_09()  throws Throwable  {
      //caseID:11f7f5e01a8d009a89039c7a75276617
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_List<PmsSkuStock>: arrayList0
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      ArrayList<PmsSkuStock> arrayList0 = new ArrayList<PmsSkuStock>();
      
      //Call method: setSkuStockList
      pmsProductParam0.setSkuStockList(arrayList0);
      
      //Test Result Assert
      assertNull(pmsProductParam0.getNote());
  }

  @Test(timeout = 4000)
  public void test_setSubjectProductRelationList_10()  throws Throwable  {
      //caseID:f2f8567e3b28434aed64d92510310ffd
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14]
      //Input_0_List<CmsSubjectProductRelation>: arrayList0
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      ArrayList<CmsSubjectProductRelation> arrayList0 = new ArrayList<CmsSubjectProductRelation>();
      
      //Call method: setSubjectProductRelationList
      pmsProductParam0.setSubjectProductRelationList(arrayList0);
      
      //Test Result Assert
      assertNull(pmsProductParam0.getDetailHtml());
  }

  @Test(timeout = 4000)
  public void test_toString_11()  throws Throwable  {
      //caseID:94a23cfa3fce593b54d94467e01c1a42
      //CoveredLines: [14, 14, 14, 14, 14, 14, 14, 14, 14, 18, 20, 22, 24, 26, 28, 30]
      //Assert: assertEquals("PmsProductParam(productLadderList=null, productFullReductionList=null, memberPriceList=null, skuStockList=null, productAttributeValueList=null, subjectProductRelationList=null, prefrenceAreaProductRelationList=null)", method_result);
      
      PmsProductParam pmsProductParam0 = new PmsProductParam();
      
      //Call method: toString
      String string0 = pmsProductParam0.toString();
      
      //Test Result Assert
      assertEquals("PmsProductParam(productLadderList=null, productFullReductionList=null, memberPriceList=null, skuStockList=null, productAttributeValueList=null, subjectProductRelationList=null, prefrenceAreaProductRelationList=null)", string0);
  }
}
