/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.dto.UmsAdminParam;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class UmsAdminParam_SSTest extends UmsAdminParam_SSTest_scaffolding {
// allCoveredLines:[15, 16, 19, 22, 24, 27, 29, 31]

  @Test(timeout = 4000)
  public void test_getEmail_00()  throws Throwable  {
      //caseID:11f9e7b050137ad4f5366127974edb82
      //CoveredLines: [16, 27]
      //Assert: assertNull(method_result);
      
      UmsAdminParam umsAdminParam0 = new UmsAdminParam();
      
      //Call method: getEmail
      String string0 = umsAdminParam0.getEmail();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getIcon_01()  throws Throwable  {
      //caseID:1e84a18af018ffca04ed005812740f5b
      //CoveredLines: [16, 24]
      //Assert: assertNull(method_result);
      
      UmsAdminParam umsAdminParam0 = new UmsAdminParam();
      
      //Call method: getIcon
      String string0 = umsAdminParam0.getIcon();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getNickName_02()  throws Throwable  {
      //caseID:fabbbb78247c05a4225711b265a32636
      //CoveredLines: [16, 29]
      //Assert: assertNull(method_result);
      
      UmsAdminParam umsAdminParam0 = new UmsAdminParam();
      
      //Call method: getNickName
      String string0 = umsAdminParam0.getNickName();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getNote_03()  throws Throwable  {
      //caseID:ca7c947cc46e15d1c059db944c66ddb2
      //CoveredLines: [16, 31]
      //Assert: assertNull(method_result);
      
      UmsAdminParam umsAdminParam0 = new UmsAdminParam();
      
      //Call method: getNote
      String string0 = umsAdminParam0.getNote();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getPassword_04()  throws Throwable  {
      //caseID:e9553f3e8543ae299955487d5e2fd6a3
      //CoveredLines: [16, 22]
      //Assert: assertNull(method_result);
      
      UmsAdminParam umsAdminParam0 = new UmsAdminParam();
      
      //Call method: getPassword
      String string0 = umsAdminParam0.getPassword();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getUsername_05()  throws Throwable  {
      //caseID:88e11635ed9c7509ffc87ba2ee7bd9dc
      //CoveredLines: [16, 19]
      //Assert: assertNull(method_result);
      
      UmsAdminParam umsAdminParam0 = new UmsAdminParam();
      
      //Call method: getUsername
      String string0 = umsAdminParam0.getUsername();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_setEmail_06()  throws Throwable  {
      //caseID:c554d50b1f7abbd01c196bb1c62992ef
      //CoveredLines: [15, 15, 15, 15, 15, 15, 16]
      //Input_0_String: 
      
      UmsAdminParam umsAdminParam0 = new UmsAdminParam();
      
      //Call method: setEmail
      umsAdminParam0.setEmail("");
      
      //Test Result Assert
      assertNull(umsAdminParam0.getIcon());
  }

  @Test(timeout = 4000)
  public void test_setIcon_07()  throws Throwable  {
      //caseID:bb9080c6a1a511c30a417f87d36f0b47
      //CoveredLines: [15, 15, 15, 15, 15, 15, 16]
      //Input_0_String: 1
      
      UmsAdminParam umsAdminParam0 = new UmsAdminParam();
      
      //Call method: setIcon
      umsAdminParam0.setIcon("1");
      
      //Test Result Assert
      assertNull(umsAdminParam0.getEmail());
  }

  @Test(timeout = 4000)
  public void test_setNickName_08()  throws Throwable  {
      //caseID:ce11a7abea65f77ae73c566e3ec53d37
      //CoveredLines: [15, 15, 15, 15, 15, 15, 16]
      //Input_0_String: 
      
      UmsAdminParam umsAdminParam0 = new UmsAdminParam();
      
      //Call method: setNickName
      umsAdminParam0.setNickName("");
      
      //Test Result Assert
      assertEquals("", umsAdminParam0.getNickName());
  }

  @Test(timeout = 4000)
  public void test_setNote_09()  throws Throwable  {
      //caseID:1183d8549ffb9de9ec92e9da801e933f
      //CoveredLines: [15, 15, 15, 15, 15, 15, 16]
      //Input_0_String: AUTO
      
      UmsAdminParam umsAdminParam0 = new UmsAdminParam();
      
      //Call method: setNote
      umsAdminParam0.setNote("AUTO");
      
      //Test Result Assert
      assertNull(umsAdminParam0.getUsername());
  }

  @Test(timeout = 4000)
  public void test_setPassword_10()  throws Throwable  {
      //caseID:886c8903312efcb94b203670da90cd03
      //CoveredLines: [15, 15, 15, 15, 15, 15, 16]
      //Input_0_String: com.macro.mall.dto.UmsAdminParam
      
      UmsAdminParam umsAdminParam0 = new UmsAdminParam();
      
      //Call method: setPassword
      umsAdminParam0.setPassword("com.macro.mall.dto.UmsAdminParam");
      
      //Test Result Assert
      assertNull(umsAdminParam0.getUsername());
  }

  @Test(timeout = 4000)
  public void test_setUsername_11()  throws Throwable  {
      //caseID:634068f10db8739ae128fbfa39e7a8cd
      //CoveredLines: [15, 15, 15, 15, 15, 15, 16]
      //Input_0_String: 1.0
      
      UmsAdminParam umsAdminParam0 = new UmsAdminParam();
      
      //Call method: setUsername
      umsAdminParam0.setUsername("1.0");
      
      //Test Result Assert
      assertNull(umsAdminParam0.getEmail());
  }
}
