/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.dto.UpdateAdminPasswordParam;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class UpdateAdminPasswordParam_SSTest extends UpdateAdminPasswordParam_SSTest_scaffolding {
// allCoveredLines:[14, 15, 18, 21, 24]

  @Test(timeout = 4000)
  public void test_getNewPassword_0()  throws Throwable  {
      //caseID:dd20a221fcdcee997bf477f1e37a128d
      //CoveredLines: [15, 24]
      //Assert: assertNull(method_result);
      
      UpdateAdminPasswordParam updateAdminPasswordParam0 = new UpdateAdminPasswordParam();
      
      //Call method: getNewPassword
      String string0 = updateAdminPasswordParam0.getNewPassword();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getOldPassword_1()  throws Throwable  {
      //caseID:2afec8b33416e630a8d9a562d83b6f6c
      //CoveredLines: [15, 21]
      //Assert: assertNull(method_result);
      
      UpdateAdminPasswordParam updateAdminPasswordParam0 = new UpdateAdminPasswordParam();
      
      //Call method: getOldPassword
      String string0 = updateAdminPasswordParam0.getOldPassword();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_getUsername_2()  throws Throwable  {
      //caseID:397cffb34775f9d4031439b9cd9f3dfa
      //CoveredLines: [15, 18]
      //Assert: assertNull(method_result);
      
      UpdateAdminPasswordParam updateAdminPasswordParam0 = new UpdateAdminPasswordParam();
      
      //Call method: getUsername
      String string0 = updateAdminPasswordParam0.getUsername();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_setNewPassword_3()  throws Throwable  {
      //caseID:7bb29041bf93b63755225c2b1d7e0127
      //CoveredLines: [14, 14, 14, 15]
      //Input_0_String: 1.0
      
      UpdateAdminPasswordParam updateAdminPasswordParam0 = new UpdateAdminPasswordParam();
      
      //Call method: setNewPassword
      updateAdminPasswordParam0.setNewPassword("1.0");
      
      //Test Result Assert
      assertEquals("1.0", updateAdminPasswordParam0.getNewPassword());
  }

  @Test(timeout = 4000)
  public void test_setOldPassword_4()  throws Throwable  {
      //caseID:e750f281a0a66d9d8f80deb963c5dbaf
      //CoveredLines: [14, 14, 14, 15]
      //Input_0_String: 
      
      UpdateAdminPasswordParam updateAdminPasswordParam0 = new UpdateAdminPasswordParam();
      
      //Call method: setOldPassword
      updateAdminPasswordParam0.setOldPassword("");
      
      //Test Result Assert
      assertNull(updateAdminPasswordParam0.getNewPassword());
  }

  @Test(timeout = 4000)
  public void test_setUsername_5()  throws Throwable  {
      //caseID:f78f67a865de3a33e267615a27d0c9b2
      //CoveredLines: [14, 14, 14, 15]
      //Input_0_String: 1.0
      
      UpdateAdminPasswordParam updateAdminPasswordParam0 = new UpdateAdminPasswordParam();
      
      //Call method: setUsername
      updateAdminPasswordParam0.setUsername("1.0");
      
      //Test Result Assert
      assertNull(updateAdminPasswordParam0.getOldPassword());
  }
}
