/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.portal.config;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.macro.mall.portal.config.JacksonConfig;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;
import org.springframework.http.converter.json.Jackson2ObjectMapperBuilder;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class JacksonConfig_SSTest extends JacksonConfig_SSTest_scaffolding {
// allCoveredLines:[18, 23, 30, 43]

  @Test(timeout = 4000)
  public void test_jacksonObjectMapper_0()  throws Throwable  {
      //caseID:416b40afb42ed87722c2f7c32a9779cd
      //CoveredLines: [18, 23, 30, 43]
      //Input_0_Jackson2ObjectMapperBuilder: {createXmlMapper=jackson2ObjectMapperBuilder0}
      //Assert: assertEquals(0, method_result.mixInCount());
      
      JacksonConfig jacksonConfig0 = new JacksonConfig();
      //mock objectMapper0
      ObjectMapper objectMapper0 = mock(ObjectMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock jackson2ObjectMapperBuilder0
      Jackson2ObjectMapperBuilder jackson2ObjectMapperBuilder0 = mock(Jackson2ObjectMapperBuilder.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(objectMapper0).when(jackson2ObjectMapperBuilder0).build();
      //mock jackson2ObjectMapperBuilder1
      Jackson2ObjectMapperBuilder jackson2ObjectMapperBuilder1 = mock(Jackson2ObjectMapperBuilder.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(jackson2ObjectMapperBuilder0).when(jackson2ObjectMapperBuilder1).createXmlMapper(anyBoolean());
      
      //Call method: jacksonObjectMapper
      ObjectMapper objectMapper1 = jacksonConfig0.jacksonObjectMapper(jackson2ObjectMapperBuilder1);
      
      //Test Result Assert
      assertEquals(0, objectMapper1.mixInCount());
  }
}
