/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.portal.config;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.portal.config.SpringTaskConfig;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SpringTaskConfig_SSTest extends SpringTaskConfig_SSTest_scaffolding {
// allCoveredLines:[12]

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      //caseID:5d1581e38852e534bc34d5ce12e10a29
      //CoveredLines: [12]
      
      SpringTaskConfig springTaskConfig0 = new SpringTaskConfig();
  }
}
