/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.search.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.search.domain.EsProductRelatedInfo;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class EsProductRelatedInfo_SSTest extends EsProductRelatedInfo_SSTest_scaffolding {
// allCoveredLines:[12, 13, 15, 16, 17, 19, 20, 22, 23, 24]

  @Test(timeout = 4000)
  public void test_equals_00()  throws Throwable  {
      //caseID:75b1bdbe0c0f0490513761851f4d3ff8
      //CoveredLines: [12, 12, 12, 12, 12, 13, 13, 13]
      //Input_0_Object: esProductRelatedInfo0
      //Assert: assertTrue(method_result);
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      
      //Call method: equals
      boolean boolean0 = esProductRelatedInfo0.equals(esProductRelatedInfo0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_01()  throws Throwable  {
      //caseID:01ce596f935abd9b681198e45e2aca06
      //CoveredLines: [12, 12, 12, 12, 12, 13, 13, 13]
      //Input_0_Object: arrayList0
      //Assert: assertFalse(method_result);
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      
      //Call method: equals
      boolean boolean0 = esProductRelatedInfo0.equals(arrayList0);
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_02()  throws Throwable  {
      //caseID:80b43003b31057640b8d2cb670065bb2
      //CoveredLines: [12, 12, 12, 12, 12, 13, 13, 13, 15, 16, 17]
      //Input_0_Object: esProductRelatedInfo0
      //Assert: assertTrue(method_result);
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      EsProductRelatedInfo esProductRelatedInfo1 = new EsProductRelatedInfo();
      
      //Call method: equals
      boolean boolean0 = esProductRelatedInfo1.equals(esProductRelatedInfo0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_03()  throws Throwable  {
      //caseID:cb19615b22bc2fafa589a480b70144fc
      //CoveredLines: [12, 12, 12, 12, 12, 13, 13, 13, 15, 16, 17]
      //Input_0_Object: esProductRelatedInfo1
      //Assert: assertTrue(method_result);
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      EsProductRelatedInfo esProductRelatedInfo1 = new EsProductRelatedInfo();
      
      //Call method: equals
      boolean boolean0 = esProductRelatedInfo0.equals(esProductRelatedInfo1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_04()  throws Throwable  {
      //caseID:dbfbb944f40fe6ac188647b145aba266
      //CoveredLines: [12, 12, 12, 12, 12, 19, 19, 19, 19, 19, 20, 20, 20]
      //Input_0_Object: esProductRelatedInfo_ProductAttr0
      //Assert: assertTrue(method_result);
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      
      //Call method: equals
      boolean boolean0 = esProductRelatedInfo_ProductAttr0.equals(esProductRelatedInfo_ProductAttr0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_05()  throws Throwable  {
      //caseID:9ebd6c41b160ffd09ea433dd577097e9
      //CoveredLines: [12, 12, 12, 12, 12, 19, 19, 19, 19, 19, 20, 20, 20]
      //Input_0_Object: esProductRelatedInfo0
      //Assert: assertFalse(method_result);
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      
      //Call method: equals
      boolean boolean0 = esProductRelatedInfo_ProductAttr0.equals(esProductRelatedInfo0);
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_06()  throws Throwable  {
      //caseID:d918a44da14652d0bb13b562c9b7596f
      //CoveredLines: [12, 12, 12, 12, 12, 19, 19, 19, 19, 19, 20, 20, 20, 22, 23, 24]
      //Input_0_Object: esProductRelatedInfo_ProductAttr1
      //Assert: assertTrue(method_result);
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr1 = new EsProductRelatedInfo.ProductAttr();
      
      //Call method: equals
      boolean boolean0 = esProductRelatedInfo_ProductAttr0.equals(esProductRelatedInfo_ProductAttr1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test_hashCode_07()  throws Throwable  {
      //caseID:1157c3633a56bedf1035d1bf442651de
      //CoveredLines: [12, 12, 12, 12, 12, 13, 13, 13, 15, 16, 17]
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      
      //Call method: hashCode
      esProductRelatedInfo0.hashCode();
  }

  @Test(timeout = 4000)
  public void test_setAttrId_08()  throws Throwable  {
      //caseID:517562841e1dc503713c4362ffd69077
      //CoveredLines: [12, 12, 12, 12, 12, 19, 19, 19, 19, 19]
      //Input_0_Long: 317L
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      Long long0 = new Long(317L);
      
      //Call method: setAttrId
      esProductRelatedInfo_ProductAttr0.setAttrId(long0);
      
      //Test Result Assert
      assertNull(esProductRelatedInfo_ProductAttr0.getAttrName());
  }

  @Test(timeout = 4000)
  public void test_setAttrName_09()  throws Throwable  {
      //caseID:2fc427b0974dbf304aa21310b2d911a2
      //CoveredLines: [12, 12, 12, 12, 12, 19, 19, 19, 19, 19]
      //Input_0_String: voting tombstones: 
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      
      //Call method: setAttrName
      esProductRelatedInfo_ProductAttr0.setAttrName("voting tombstones: ");
      
      //Test Result Assert
      assertEquals("voting tombstones: ", esProductRelatedInfo_ProductAttr0.getAttrName());
  }

  @Test(timeout = 4000)
  public void test_setAttrValues_10()  throws Throwable  {
      //caseID:5596e9f1c1d2b1495d4854597730c28d
      //CoveredLines: [12, 12, 12, 12, 12, 19, 19, 19, 19, 19]
      //Input_0_List<String>: linkedList0
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      
      //Call method: setAttrValues
      esProductRelatedInfo_ProductAttr0.setAttrValues(linkedList0);
      
      //Test Result Assert
      assertNull(esProductRelatedInfo_ProductAttr0.getAttrName());
  }

  @Test(timeout = 4000)
  public void test_setBrandNames_11()  throws Throwable  {
      //caseID:63f264a73b5d0d2a2b641d93fa905d8a
      //CoveredLines: [12, 12, 12, 12, 12]
      //Input_0_List<String>: vector0
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      Vector<String> vector0 = new Vector<String>();
      
      //Call method: setBrandNames
      esProductRelatedInfo0.setBrandNames(vector0);
      
      //Test Result Assert
      assertTrue(vector0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test_setProductAttrs_12()  throws Throwable  {
      //caseID:b99d3999faa2b72f9ceac84490287a67
      //CoveredLines: [12, 12, 12, 12, 12]
      //Input_0_List<EsProductRelatedInfo.ProductAttr>: arrayList0
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      ArrayList<EsProductRelatedInfo.ProductAttr> arrayList0 = new ArrayList<EsProductRelatedInfo.ProductAttr>();
      
      //Call method: setProductAttrs
      esProductRelatedInfo0.setProductAttrs(arrayList0);
      
      //Test Result Assert
      assertTrue(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test_setProductCategoryNames_13()  throws Throwable  {
      //caseID:347f28ec66ce3f7d93300f403f3b05e4
      //CoveredLines: [12, 12, 12, 12, 12]
      //Input_0_List<String>: vector0
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      Vector<String> vector0 = new Vector<String>();
      
      //Call method: setProductCategoryNames
      esProductRelatedInfo0.setProductCategoryNames(vector0);
      
      //Test Result Assert
      assertTrue(vector0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test_toString_14()  throws Throwable  {
      //caseID:bae5e1974fe6f9d78da6ab90df118f24
      //CoveredLines: [12, 12, 12, 12, 12, 15, 16, 17]
      //Assert: assertEquals("EsProductRelatedInfo(brandNames=null, productCategoryNames=null, productAttrs=null)", method_result);
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      
      //Call method: toString
      String string0 = esProductRelatedInfo0.toString();
      
      //Test Result Assert
      assertEquals("EsProductRelatedInfo(brandNames=null, productCategoryNames=null, productAttrs=null)", string0);
  }

  @Test(timeout = 4000)
  public void test_toString_15()  throws Throwable  {
      //caseID:f74c348eb413bec3d1e51adf0b387de1
      //CoveredLines: [12, 12, 12, 12, 12, 19, 19, 19, 19, 19, 22, 23, 24]
      //Assert: assertEquals("EsProductRelatedInfo.ProductAttr(attrId=null, attrName=null, attrValues=null)", method_result);
      
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      
      //Call method: toString
      String string0 = esProductRelatedInfo_ProductAttr0.toString();
      
      //Test Result Assert
      assertEquals("EsProductRelatedInfo.ProductAttr(attrId=null, attrName=null, attrValues=null)", string0);
  }
}
