/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.service.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.macro.mall.dao.PmsProductAttributeCategoryDao;
import com.macro.mall.dto.PmsProductAttributeCategoryItem;
import com.macro.mall.mapper.PmsProductAttributeCategoryMapper;
import com.macro.mall.model.PmsProductAttributeCategory;
import com.macro.mall.service.impl.PmsProductAttributeCategoryServiceImpl;
import java.util.List;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class PmsProductAttributeCategoryServiceImpl_SSTest extends PmsProductAttributeCategoryServiceImpl_SSTest_scaffolding {
// allCoveredLines:[20, 28, 29, 30, 35, 36, 37, 38, 43, 48, 53, 54, 59]

  @Test(timeout = 4000)
  public void test_create_0()  throws Throwable  {
      //caseID:0ab902fbc76bac55703e3740708dedfa
      //CoveredLines: [20, 28, 29, 30]
      //Input_0_String: "com.macro.mall.service.impl.PmsProductAttributeCategoryServiceImpl"
      //Assert: assertEquals(0, method_result);
      
      PmsProductAttributeCategoryServiceImpl pmsProductAttributeCategoryServiceImpl0 = new PmsProductAttributeCategoryServiceImpl();
      //mock pmsProductAttributeCategoryMapper0
      PmsProductAttributeCategoryMapper pmsProductAttributeCategoryMapper0 = mock(PmsProductAttributeCategoryMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      PrivateAccess.setVariable((Class<?>) PmsProductAttributeCategoryServiceImpl.class, pmsProductAttributeCategoryServiceImpl0, "productAttributeCategoryMapper", (Object) pmsProductAttributeCategoryMapper0);
      
      //Call method: create
      int int0 = pmsProductAttributeCategoryServiceImpl0.create("com.macro.mall.service.impl.PmsProductAttributeCategoryServiceImpl");
      
      //Test Result Assert
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test_delete_1()  throws Throwable  {
      //caseID:fb5e4a79d44c6b0c7cfdd9097157d27e
      //CoveredLines: [20, 43]
      //Input_0_Long: (-1L)
      //Assert: assertEquals(0, method_result);
      
      PmsProductAttributeCategoryServiceImpl pmsProductAttributeCategoryServiceImpl0 = new PmsProductAttributeCategoryServiceImpl();
      //mock pmsProductAttributeCategoryMapper0
      PmsProductAttributeCategoryMapper pmsProductAttributeCategoryMapper0 = mock(PmsProductAttributeCategoryMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      PrivateAccess.setVariable((Class<?>) PmsProductAttributeCategoryServiceImpl.class, pmsProductAttributeCategoryServiceImpl0, "productAttributeCategoryMapper", (Object) pmsProductAttributeCategoryMapper0);
      Long long0 = new Long((-1L));
      
      //Call method: delete
      int int0 = pmsProductAttributeCategoryServiceImpl0.delete(long0);
      
      //Test Result Assert
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test_getItem_2()  throws Throwable  {
      //caseID:534aca61c7c1a203f767180b296477dc
      //CoveredLines: [20, 48]
      //Input_0_Long: 0L
      //Assert: assertNull(method_result);
      
      PmsProductAttributeCategoryServiceImpl pmsProductAttributeCategoryServiceImpl0 = new PmsProductAttributeCategoryServiceImpl();
      //mock pmsProductAttributeCategoryMapper0
      PmsProductAttributeCategoryMapper pmsProductAttributeCategoryMapper0 = mock(PmsProductAttributeCategoryMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      PrivateAccess.setVariable((Class<?>) PmsProductAttributeCategoryServiceImpl.class, pmsProductAttributeCategoryServiceImpl0, "productAttributeCategoryMapper", (Object) pmsProductAttributeCategoryMapper0);
      Long long0 = new Long(0L);
      
      //Call method: getItem
      PmsProductAttributeCategory pmsProductAttributeCategory0 = pmsProductAttributeCategoryServiceImpl0.getItem(long0);
      
      //Test Result Assert
      assertNull(pmsProductAttributeCategory0);
  }

  @Test(timeout = 4000)
  public void test_getList_3()  throws Throwable  {
      //caseID:643d6055ef63e592a3d69192c9aecd5c
      //CoveredLines: [20, 53, 54]
      //Input_0_Integer: (-1)
      //Input_1_Integer: (-1)
      //Assert: assertNull(method_result);
      
      PmsProductAttributeCategoryServiceImpl pmsProductAttributeCategoryServiceImpl0 = new PmsProductAttributeCategoryServiceImpl();
      //mock pmsProductAttributeCategoryMapper0
      PmsProductAttributeCategoryMapper pmsProductAttributeCategoryMapper0 = mock(PmsProductAttributeCategoryMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      PrivateAccess.setVariable((Class<?>) PmsProductAttributeCategoryServiceImpl.class, pmsProductAttributeCategoryServiceImpl0, "productAttributeCategoryMapper", (Object) pmsProductAttributeCategoryMapper0);
      Integer integer0 = new Integer((-1));
      
      //Call method: getList
      List<PmsProductAttributeCategory> list0 = pmsProductAttributeCategoryServiceImpl0.getList(integer0, integer0);
      
      //Test Result Assert
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test_getListWithAttr_4()  throws Throwable  {
      //caseID:6f88d8a624e2d798d2873799cdd4ca89
      //CoveredLines: [20, 59]
      //Assert: assertNull(method_result);
      
      PmsProductAttributeCategoryServiceImpl pmsProductAttributeCategoryServiceImpl0 = new PmsProductAttributeCategoryServiceImpl();
      //mock pmsProductAttributeCategoryDao0
      PmsProductAttributeCategoryDao pmsProductAttributeCategoryDao0 = mock(PmsProductAttributeCategoryDao.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      PrivateAccess.setVariable((Class<?>) PmsProductAttributeCategoryServiceImpl.class, pmsProductAttributeCategoryServiceImpl0, "productAttributeCategoryDao", (Object) pmsProductAttributeCategoryDao0);
      
      //Call method: getListWithAttr
      List<PmsProductAttributeCategoryItem> list0 = pmsProductAttributeCategoryServiceImpl0.getListWithAttr();
      
      //Test Result Assert
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test_update_5()  throws Throwable  {
      //caseID:99060a70982f21d925a0b2018ff56471
      //CoveredLines: [20, 35, 36, 37, 38]
      //Input_0_Long: 2300L
      //Input_1_String: "1"
      //Assert: assertEquals(0, method_result);
      
      PmsProductAttributeCategoryServiceImpl pmsProductAttributeCategoryServiceImpl0 = new PmsProductAttributeCategoryServiceImpl();
      //mock pmsProductAttributeCategoryMapper0
      PmsProductAttributeCategoryMapper pmsProductAttributeCategoryMapper0 = mock(PmsProductAttributeCategoryMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      PrivateAccess.setVariable((Class<?>) PmsProductAttributeCategoryServiceImpl.class, pmsProductAttributeCategoryServiceImpl0, "productAttributeCategoryMapper", (Object) pmsProductAttributeCategoryMapper0);
      Long long0 = new Long(2300L);
      
      //Call method: update
      int int0 = pmsProductAttributeCategoryServiceImpl0.update(long0, "1");
      
      //Test Result Assert
      assertEquals(0, int0);
  }
}
