/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.demo.config;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.demo.config.MyBatisConfig;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class MyBatisConfig_SSTest extends MyBatisConfig_SSTest_scaffolding {
// allCoveredLines:[12]

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      //caseID:9b7d3aa32b357220aeaf58382b9ded26
      //CoveredLines: [12]
      
      MyBatisConfig myBatisConfig0 = new MyBatisConfig();
  }
}
