/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.security.component;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import static org.smartunit.runtime.SmartAssertions.*;
import com.macro.mall.security.component.DynamicAccessDecisionManager;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.PriorityQueue;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;
import org.springframework.security.access.ConfigAttribute;
import org.springframework.security.access.SecurityConfig;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class DynamicAccessDecisionManager_SSTest extends DynamicAccessDecisionManager_SSTest_scaffolding {
// allCoveredLines:[18, 24, 25, 27, 28, 29, 31, 32, 33, 34, 36, 37, 38, 43, 48]

  @Test(timeout = 4000)
  public void test_decide_0()  throws Throwable  {
      //caseID:2d3b777739ed4476a411d0c12698c0dc
      //CoveredLines: [18, 24, 25]
      //Input_0_Authentication: {}
      //Input_1_Object: {}
      //Input_2_Collection<ConfigAttribute>: linkedList0
      
      DynamicAccessDecisionManager dynamicAccessDecisionManager0 = new DynamicAccessDecisionManager();
      //mock authentication0
      Authentication authentication0 = mock(Authentication.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      LinkedList<ConfigAttribute> linkedList0 = new LinkedList<ConfigAttribute>();
      
      //Call method: decide
      dynamicAccessDecisionManager0.decide(authentication0, authentication0, linkedList0);
      
      //Test Result Assert
      assertEquals(0, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test_decide_1()  throws Throwable  {
      //caseID:3b4b4e1cfabf27a79841056fc1fc75b8
      //CoveredLines: [18, 24, 27, 28, 29, 31, 32, 33, 34]
      //Input_0_Authentication: {getAuthorities=priorityQueue0}
      //Input_1_Object: {getAuthorities=priorityQueue0}
      //Input_2_Collection<ConfigAttribute>: linkedList0
      
      DynamicAccessDecisionManager dynamicAccessDecisionManager0 = new DynamicAccessDecisionManager();
      PriorityQueue<GrantedAuthority> priorityQueue0 = new PriorityQueue<GrantedAuthority>();
      //mock grantedAuthority0
      GrantedAuthority grantedAuthority0 = mock(GrantedAuthority.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("").when(grantedAuthority0).getAuthority();
      
      priorityQueue0.add(grantedAuthority0);
      //mock authentication0
      Authentication authentication0 = mock(Authentication.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(priorityQueue0).when(authentication0).getAuthorities();
      LinkedList<ConfigAttribute> linkedList0 = new LinkedList<ConfigAttribute>();
      //mock configAttribute0
      ConfigAttribute configAttribute0 = mock(ConfigAttribute.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("").when(configAttribute0).getAttribute();
      
      linkedList0.add(configAttribute0);
      
      //Call method: decide
      dynamicAccessDecisionManager0.decide(authentication0, authentication0, linkedList0);
      
      //Test Result Assert
      assertEquals(1, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test_decide_2()  throws Throwable  {
      //caseID:cb8fb49e65b8012776fb03412c82aa75
      //CoveredLines: [18, 24, 27, 28, 29, 31, 32, 33, 36, 37, 38]
      //Input_0_Authentication: {getAuthorities=arrayList0}
      //Input_1_Object: {getAuthorities=arrayList0}
      //Input_2_Collection<ConfigAttribute>: linkedHashSet0
      
      DynamicAccessDecisionManager dynamicAccessDecisionManager0 = new DynamicAccessDecisionManager();
      ArrayList<SimpleGrantedAuthority> arrayList0 = new ArrayList<SimpleGrantedAuthority>();
      //mock simpleGrantedAuthority0
      SimpleGrantedAuthority simpleGrantedAuthority0 = mock(SimpleGrantedAuthority.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      arrayList0.add(simpleGrantedAuthority0);
      //mock authentication0
      Authentication authentication0 = mock(Authentication.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(arrayList0).when(authentication0).getAuthorities();
      LinkedHashSet<ConfigAttribute> linkedHashSet0 = new LinkedHashSet<ConfigAttribute>();
      //mock configAttribute0
      ConfigAttribute configAttribute0 = mock(ConfigAttribute.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("1").when(configAttribute0).getAttribute();
      
      linkedHashSet0.add(configAttribute0);
      
      //Call method: decide
      try { 
        dynamicAccessDecisionManager0.decide(authentication0, authentication0, linkedHashSet0);
      } catch(Throwable e) {
         verifyException("com.macro.mall.security.component.DynamicAccessDecisionManager", e);
         assertEquals("org.springframework.security.access.AccessDeniedException", e.getClass().getName());
         assertEquals("\u62B1\u6B49\uFF0C\u60A8\u6CA1\u6709\u8BBF\u95EE\u6743\u9650", e.getMessage());
      }
  }

  @Test(timeout = 4000)
  public void test_supports_3()  throws Throwable  {
      //caseID:f57f386820f434c997fa52c3f8819fee
      //CoveredLines: [18, 43]
      //Input_0_ConfigAttribute: {}
      //Assert: assertTrue(method_result);
      
      DynamicAccessDecisionManager dynamicAccessDecisionManager0 = new DynamicAccessDecisionManager();
      //mock configAttribute0
      ConfigAttribute configAttribute0 = mock(ConfigAttribute.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: supports
      boolean boolean0 = dynamicAccessDecisionManager0.supports(configAttribute0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test_supports_4()  throws Throwable  {
      //caseID:6fa6889ab85b575ccafb79bb65788e92
      //CoveredLines: [18, 48]
      //Input_0_Class<?>: SecurityConfig.class
      //Assert: assertTrue(method_result);
      
      DynamicAccessDecisionManager dynamicAccessDecisionManager0 = new DynamicAccessDecisionManager();
      Class<SecurityConfig> class0 = SecurityConfig.class;
      
      //Call method: supports
      boolean boolean0 = dynamicAccessDecisionManager0.supports(class0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }
}
