/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.security.component;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import static org.smartunit.runtime.SmartAssertions.*;
import com.macro.mall.security.component.DynamicAccessDecisionManager;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.PriorityQueue;
import java.util.Stack;
import java.util.Vector;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;
import org.springframework.security.access.ConfigAttribute;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class DynamicAccessDecisionManager_SSTest extends DynamicAccessDecisionManager_SSTest_scaffolding {
// allCoveredLines:[18, 24, 25, 27, 28, 29, 31, 32, 33, 34, 36, 37, 38, 43, 48]

  @Test(timeout = 4000)
  public void test_decide_0()  throws Throwable  {
      //caseID:e776596244c9e5658c6b20e70aa4d40f
      //CoveredLines: [18, 24, 25]
      //Input_0_Authentication: {}
      //Input_1_Object: {}
      //Input_2_Collection<ConfigAttribute>: arrayList0
      
      DynamicAccessDecisionManager dynamicAccessDecisionManager0 = new DynamicAccessDecisionManager();
      //mock authentication0
      Authentication authentication0 = mock(Authentication.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      ArrayList<ConfigAttribute> arrayList0 = new ArrayList<ConfigAttribute>();
      
      //Call method: decide
      dynamicAccessDecisionManager0.decide(authentication0, authentication0, arrayList0);
      
      //Test Result Assert
      assertTrue(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test_decide_1()  throws Throwable  {
      //caseID:4a8dcc6427d422e01520a82e33e6ae42
      //CoveredLines: [18, 24, 27, 28, 29, 31, 32, 33, 34]
      //Input_0_Authentication: {getAuthorities=priorityQueue0}
      //Input_1_Object: {getAuthorities=priorityQueue0}
      //Input_2_Collection<ConfigAttribute>: hashSet0
      
      DynamicAccessDecisionManager dynamicAccessDecisionManager0 = new DynamicAccessDecisionManager();
      PriorityQueue<SimpleGrantedAuthority> priorityQueue0 = new PriorityQueue<SimpleGrantedAuthority>();
      //mock simpleGrantedAuthority0
      SimpleGrantedAuthority simpleGrantedAuthority0 = mock(SimpleGrantedAuthority.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("%`D++/").when(simpleGrantedAuthority0).getAuthority();
      
      priorityQueue0.add(simpleGrantedAuthority0);
      //mock authentication0
      Authentication authentication0 = mock(Authentication.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(priorityQueue0).when(authentication0).getAuthorities();
      HashSet<ConfigAttribute> hashSet0 = new HashSet<ConfigAttribute>();
      //mock configAttribute0
      ConfigAttribute configAttribute0 = mock(ConfigAttribute.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("%`D++/").when(configAttribute0).getAttribute();
      
      hashSet0.add(configAttribute0);
      
      //Call method: decide
      dynamicAccessDecisionManager0.decide(authentication0, authentication0, hashSet0);
      
      //Test Result Assert
      assertEquals(1, hashSet0.size());
  }

  @Test(timeout = 4000)
  public void test_decide_2()  throws Throwable  {
      //caseID:59dffbdd9432716ccc0bdfecbe66c691
      //CoveredLines: [18, 24, 27, 28, 29, 31, 32, 33, 36, 37, 38]
      //Input_0_Authentication: {getAuthorities=stack0}
      //Input_1_Object: {getAuthorities=stack0}
      //Input_2_Collection<ConfigAttribute>: vector0
      
      DynamicAccessDecisionManager dynamicAccessDecisionManager0 = new DynamicAccessDecisionManager();
      Stack<GrantedAuthority> stack0 = new Stack<GrantedAuthority>();
      //mock grantedAuthority0
      GrantedAuthority grantedAuthority0 = mock(GrantedAuthority.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      stack0.add(grantedAuthority0);
      //mock authentication0
      Authentication authentication0 = mock(Authentication.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(stack0).when(authentication0).getAuthorities();
      Vector<ConfigAttribute> vector0 = new Vector<ConfigAttribute>();
      //mock configAttribute0
      ConfigAttribute configAttribute0 = mock(ConfigAttribute.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("com.macro.mall.security.component.DynamicAccessDecisionManager").when(configAttribute0).getAttribute();
      
      vector0.add(configAttribute0);
      
      //Call method: decide
      try { 
        dynamicAccessDecisionManager0.decide(authentication0, authentication0, vector0);
      } catch(Throwable e) {
         verifyException("com.macro.mall.security.component.DynamicAccessDecisionManager", e);
         assertEquals("org.springframework.security.access.AccessDeniedException", e.getClass().getName());
         assertEquals("\u62B1\u6B49\uFF0C\u60A8\u6CA1\u6709\u8BBF\u95EE\u6743\u9650", e.getMessage());
      }
  }

  @Test(timeout = 4000)
  public void test_supports_3()  throws Throwable  {
      //caseID:610756c75c5966f9f475c281e44b6dde
      //CoveredLines: [18, 48]
      //Input_0_Class<?>: ConfigAttribute.class
      //Assert: assertTrue(method_result);
      
      DynamicAccessDecisionManager dynamicAccessDecisionManager0 = new DynamicAccessDecisionManager();
      Class<ConfigAttribute> class0 = ConfigAttribute.class;
      
      //Call method: supports
      boolean boolean0 = dynamicAccessDecisionManager0.supports(class0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test_supports_4()  throws Throwable  {
      //caseID:605c878e1b6ab0c1f43544a4b968d7fb
      //CoveredLines: [18, 43]
      //Input_0_ConfigAttribute: {}
      //Assert: assertTrue(method_result);
      
      DynamicAccessDecisionManager dynamicAccessDecisionManager0 = new DynamicAccessDecisionManager();
      //mock configAttribute0
      ConfigAttribute configAttribute0 = mock(ConfigAttribute.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: supports
      boolean boolean0 = dynamicAccessDecisionManager0.supports(configAttribute0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }
}
