/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.macro.mall.common.api.CommonResult;
import com.macro.mall.controller.SmsFlashPromotionController;
import com.macro.mall.model.SmsFlashPromotion;
import com.macro.mall.service.SmsFlashPromotionService;
import java.util.Vector;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SmsFlashPromotionController_SSTest extends SmsFlashPromotionController_SSTest_scaffolding {
// allCoveredLines:[22, 30, 31, 32, 34, 41, 42, 43, 45, 52, 53, 54, 56, 63, 64, 65, 67, 74, 75, 84, 85]

  @Test(timeout = 4000)
  public void test_create_0()  throws Throwable  {
      //caseID:93ac1b154cc3130922a7d93156aafe07
      //CoveredLines: [22, 30, 31, 32]
      //Input_0_SmsFlashPromotion: {}
      //Assert: assertEquals(200L, method_result.getCode());
      
      SmsFlashPromotionController smsFlashPromotionController0 = new SmsFlashPromotionController();
      //mock smsFlashPromotionService0
      SmsFlashPromotionService smsFlashPromotionService0 = mock(SmsFlashPromotionService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(19).when(smsFlashPromotionService0).create(any(com.macro.mall.model.SmsFlashPromotion.class));
      PrivateAccess.setVariable((Class<?>) SmsFlashPromotionController.class, smsFlashPromotionController0, "flashPromotionService", (Object) smsFlashPromotionService0);
      //mock smsFlashPromotion0
      SmsFlashPromotion smsFlashPromotion0 = mock(SmsFlashPromotion.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: create
      CommonResult commonResult0 = smsFlashPromotionController0.create(smsFlashPromotion0);
      
      //Test Result Assert
      assertEquals(200L, commonResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test_create_1()  throws Throwable  {
      //caseID:0ca02616d6c2bb45728b84d12d2db56c
      //CoveredLines: [22, 30, 31, 34]
      //Input_0_SmsFlashPromotion: {}
      //Assert: assertEquals(500L, method_result.getCode());
      
      SmsFlashPromotionController smsFlashPromotionController0 = new SmsFlashPromotionController();
      //mock smsFlashPromotionService0
      SmsFlashPromotionService smsFlashPromotionService0 = mock(SmsFlashPromotionService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      PrivateAccess.setVariable((Class<?>) SmsFlashPromotionController.class, smsFlashPromotionController0, "flashPromotionService", (Object) smsFlashPromotionService0);
      //mock smsFlashPromotion0
      SmsFlashPromotion smsFlashPromotion0 = mock(SmsFlashPromotion.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: create
      CommonResult commonResult0 = smsFlashPromotionController0.create(smsFlashPromotion0);
      
      //Test Result Assert
      assertEquals(500L, commonResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test_delete_2()  throws Throwable  {
      //caseID:2db3f7a5eb4367c38bcb5cd4477ca42b
      //CoveredLines: [22, 52, 53, 54]
      //Input_0_Long: 1
      //Assert: assertEquals(200L, method_result.getCode());
      
      SmsFlashPromotionController smsFlashPromotionController0 = new SmsFlashPromotionController();
      //mock smsFlashPromotionService0
      SmsFlashPromotionService smsFlashPromotionService0 = mock(SmsFlashPromotionService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(1).when(smsFlashPromotionService0).delete(anyLong());
      PrivateAccess.setVariable((Class<?>) SmsFlashPromotionController.class, smsFlashPromotionController0, "flashPromotionService", (Object) smsFlashPromotionService0);
      Long long0 = new Long(1);
      
      //Call method: delete
      CommonResult commonResult0 = (CommonResult)smsFlashPromotionController0.delete(long0);
      
      //Test Result Assert
      assertEquals(200L, commonResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test_delete_3()  throws Throwable  {
      //caseID:3d69a80841aa4ffd7ea316d89c595c74
      //CoveredLines: [22, 52, 53, 56]
      //Input_0_Long: 0L
      //Assert: assertEquals(500L, method_result.getCode());
      
      SmsFlashPromotionController smsFlashPromotionController0 = new SmsFlashPromotionController();
      //mock smsFlashPromotionService0
      SmsFlashPromotionService smsFlashPromotionService0 = mock(SmsFlashPromotionService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      PrivateAccess.setVariable((Class<?>) SmsFlashPromotionController.class, smsFlashPromotionController0, "flashPromotionService", (Object) smsFlashPromotionService0);
      Long long0 = new Long(0L);
      
      //Call method: delete
      CommonResult commonResult0 = (CommonResult)smsFlashPromotionController0.delete(long0);
      
      //Test Result Assert
      assertEquals(500L, commonResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test_getItem_4()  throws Throwable  {
      //caseID:8185f673c8831bb6f7c12e3e2844fb4c
      //CoveredLines: [22, 84, 85]
      //Input_0_String: "1.0"
      //Input_1_Integer: 0
      //Input_2_Integer: 0
      //Assert: assertEquals("\u64CD\u4F5C\u6210\u529F", method_result.getMessage());
      
      SmsFlashPromotionController smsFlashPromotionController0 = new SmsFlashPromotionController();
      Vector<SmsFlashPromotion> vector0 = new Vector<SmsFlashPromotion>();
      //mock smsFlashPromotionService0
      SmsFlashPromotionService smsFlashPromotionService0 = mock(SmsFlashPromotionService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(vector0).when(smsFlashPromotionService0).list(anyString() , anyInt() , anyInt());
      PrivateAccess.setVariable((Class<?>) SmsFlashPromotionController.class, smsFlashPromotionController0, "flashPromotionService", (Object) smsFlashPromotionService0);
      Integer integer0 = new Integer(0);
      
      //Call method: getItem
      CommonResult commonResult0 = (CommonResult)smsFlashPromotionController0.getItem("1.0", integer0, integer0);
      
      //Test Result Assert
      assertEquals("\u64CD\u4F5C\u6210\u529F", commonResult0.getMessage());
  }

  @Test(timeout = 4000)
  public void test_getItem_5()  throws Throwable  {
      //caseID:0b36c1f551819f7e3c324a09a2d0bf9c
      //CoveredLines: [22, 74, 75]
      //Input_0_Long: 0L
      //Assert: assertEquals(200L, method_result.getCode());
      
      SmsFlashPromotionController smsFlashPromotionController0 = new SmsFlashPromotionController();
      //mock smsFlashPromotionService0
      SmsFlashPromotionService smsFlashPromotionService0 = mock(SmsFlashPromotionService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      PrivateAccess.setVariable((Class<?>) SmsFlashPromotionController.class, smsFlashPromotionController0, "flashPromotionService", (Object) smsFlashPromotionService0);
      Long long0 = new Long(0L);
      
      //Call method: getItem
      CommonResult commonResult0 = (CommonResult)smsFlashPromotionController0.getItem(long0);
      
      //Test Result Assert
      assertEquals(200L, commonResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test_update_6()  throws Throwable  {
      //caseID:bed5ffa13e60675ea06399ce1165f4b3
      //CoveredLines: [22, 41, 42, 43]
      //Input_0_Long: 26
      //Input_1_SmsFlashPromotion: {}
      //Assert: assertEquals("\u64CD\u4F5C\u6210\u529F", method_result.getMessage());
      
      SmsFlashPromotionController smsFlashPromotionController0 = new SmsFlashPromotionController();
      //mock smsFlashPromotionService0
      SmsFlashPromotionService smsFlashPromotionService0 = mock(SmsFlashPromotionService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(26).when(smsFlashPromotionService0).update(anyLong() , any(com.macro.mall.model.SmsFlashPromotion.class));
      PrivateAccess.setVariable((Class<?>) SmsFlashPromotionController.class, smsFlashPromotionController0, "flashPromotionService", (Object) smsFlashPromotionService0);
      Long long0 = new Long(26);
      //mock smsFlashPromotion0
      SmsFlashPromotion smsFlashPromotion0 = mock(SmsFlashPromotion.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: update
      CommonResult commonResult0 = (CommonResult)smsFlashPromotionController0.update(long0, smsFlashPromotion0);
      
      //Test Result Assert
      assertEquals("\u64CD\u4F5C\u6210\u529F", commonResult0.getMessage());
  }

  @Test(timeout = 4000)
  public void test_update_7()  throws Throwable  {
      //caseID:7c6c5e1f7fbf58fb14ebba808ffc41a4
      //CoveredLines: [22, 41, 42, 45]
      //Input_0_Long: (-1L)
      //Input_1_SmsFlashPromotion: {}
      //Assert: assertEquals("\u64CD\u4F5C\u5931\u8D25", method_result.getMessage());
      
      SmsFlashPromotionController smsFlashPromotionController0 = new SmsFlashPromotionController();
      //mock smsFlashPromotionService0
      SmsFlashPromotionService smsFlashPromotionService0 = mock(SmsFlashPromotionService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      PrivateAccess.setVariable((Class<?>) SmsFlashPromotionController.class, smsFlashPromotionController0, "flashPromotionService", (Object) smsFlashPromotionService0);
      Long long0 = new Long((-1L));
      //mock smsFlashPromotion0
      SmsFlashPromotion smsFlashPromotion0 = mock(SmsFlashPromotion.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: update
      CommonResult commonResult0 = (CommonResult)smsFlashPromotionController0.update(long0, smsFlashPromotion0);
      
      //Test Result Assert
      assertEquals("\u64CD\u4F5C\u5931\u8D25", commonResult0.getMessage());
  }

  @Test(timeout = 4000)
  public void test_update_8()  throws Throwable  {
      //caseID:dc0de453de062d4c80428046956425be
      //CoveredLines: [22, 63, 64, 65]
      //Input_0_Long: 240
      //Input_1_Integer: 240
      //Assert: assertEquals("\u64CD\u4F5C\u6210\u529F", method_result.getMessage());
      
      SmsFlashPromotionController smsFlashPromotionController0 = new SmsFlashPromotionController();
      //mock smsFlashPromotionService0
      SmsFlashPromotionService smsFlashPromotionService0 = mock(SmsFlashPromotionService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(240).when(smsFlashPromotionService0).updateStatus(anyLong() , anyInt());
      PrivateAccess.setVariable((Class<?>) SmsFlashPromotionController.class, smsFlashPromotionController0, "flashPromotionService", (Object) smsFlashPromotionService0);
      Long long0 = new Long(240);
      Integer integer0 = new Integer(240);
      
      //Call method: update
      CommonResult commonResult0 = (CommonResult)smsFlashPromotionController0.update(long0, integer0);
      
      //Test Result Assert
      assertEquals("\u64CD\u4F5C\u6210\u529F", commonResult0.getMessage());
  }

  @Test(timeout = 4000)
  public void test_update_9()  throws Throwable  {
      //caseID:348529695982586fb668a81703b57c90
      //CoveredLines: [22, 63, 64, 67]
      //Input_0_Long: (-1)
      //Input_1_Integer: (-1)
      //Assert: assertEquals(500L, method_result.getCode());
      
      SmsFlashPromotionController smsFlashPromotionController0 = new SmsFlashPromotionController();
      //mock smsFlashPromotionService0
      SmsFlashPromotionService smsFlashPromotionService0 = mock(SmsFlashPromotionService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn((-1)).when(smsFlashPromotionService0).updateStatus(anyLong() , anyInt());
      PrivateAccess.setVariable((Class<?>) SmsFlashPromotionController.class, smsFlashPromotionController0, "flashPromotionService", (Object) smsFlashPromotionService0);
      Long long0 = new Long((-1));
      Integer integer0 = new Integer((-1));
      
      //Call method: update
      CommonResult commonResult0 = (CommonResult)smsFlashPromotionController0.update(long0, integer0);
      
      //Test Result Assert
      assertEquals(500L, commonResult0.getCode());
  }
}
