/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.common.api;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.common.api.ResultCode;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ResultCode_SSTest extends ResultCode_SSTest_scaffolding {
// allCoveredLines:[22, 26]

  @Test(timeout = 4000)
  public void test_getCode_0()  throws Throwable  {
      //caseID:945a3164b2c92150b339789b8ae30327
      //CoveredLines: [22]
      
      ResultCode resultCode0 = ResultCode.FORBIDDEN;
      
      //Call method: getCode
      resultCode0.getCode();
  }

  @Test(timeout = 4000)
  public void test_getMessage_1()  throws Throwable  {
      //caseID:74c1ab9ee76a8bf7ceaac2d5590b7297
      //CoveredLines: [26]
      
      ResultCode resultCode0 = ResultCode.FAILED;
      
      //Call method: getMessage
      resultCode0.getMessage();
  }
}
