/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.portal.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.macro.mall.model.UmsIntegrationConsumeSetting;
import com.macro.mall.model.UmsMemberReceiveAddress;
import com.macro.mall.portal.domain.CartPromotionItem;
import com.macro.mall.portal.domain.ConfirmOrderResult;
import com.macro.mall.portal.domain.SmsCouponHistoryDetail;
import java.util.ArrayList;
import java.util.List;
import java.util.Stack;
import java.util.Vector;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ConfirmOrderResult_SSTest extends ConfirmOrderResult_SSTest_scaffolding {
// allCoveredLines:[13, 28, 32, 33, 36, 40, 41, 44, 48, 49, 52, 56, 57, 60, 64, 65, 68, 72, 73]

  @Test(timeout = 4000)
  public void test_getCalcAmount_00()  throws Throwable  {
      //caseID:89791296f358e5bc99746413366b6f49
      //CoveredLines: [13, 68]
      //Assert: assertNull(method_result);
      
      ConfirmOrderResult confirmOrderResult0 = new ConfirmOrderResult();
      
      //Call method: getCalcAmount
      ConfirmOrderResult.CalcAmount confirmOrderResult_CalcAmount0 = confirmOrderResult0.getCalcAmount();
      
      //Test Result Assert
      assertNull(confirmOrderResult_CalcAmount0);
  }

  @Test(timeout = 4000)
  public void test_getCartPromotionItemList_01()  throws Throwable  {
      //caseID:5eba90f2777f2a128ffaebc585401552
      //CoveredLines: [13, 28]
      //Assert: assertTrue(method_result.isEmpty());
      
      ConfirmOrderResult confirmOrderResult0 = new ConfirmOrderResult();
      Vector<CartPromotionItem> vector0 = new Vector<CartPromotionItem>();
      PrivateAccess.setVariable((Class<?>) ConfirmOrderResult.class, confirmOrderResult0, "cartPromotionItemList", (Object) vector0);
      
      //Call method: getCartPromotionItemList
      List<CartPromotionItem> list0 = confirmOrderResult0.getCartPromotionItemList();
      
      //Test Result Assert
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test_getCouponHistoryDetailList_02()  throws Throwable  {
      //caseID:4ba5fde2daa1fc6872e8d9cd1148d11d
      //CoveredLines: [13, 44]
      //Assert: assertNull(method_result);
      
      ConfirmOrderResult confirmOrderResult0 = new ConfirmOrderResult();
      
      //Call method: getCouponHistoryDetailList
      List<SmsCouponHistoryDetail> list0 = confirmOrderResult0.getCouponHistoryDetailList();
      
      //Test Result Assert
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test_getIntegrationConsumeSetting_03()  throws Throwable  {
      //caseID:a4cf436d895e7fbc198425908dc3c331
      //CoveredLines: [13, 52]
      //Assert: assertNull(method_result);
      
      ConfirmOrderResult confirmOrderResult0 = new ConfirmOrderResult();
      
      //Call method: getIntegrationConsumeSetting
      UmsIntegrationConsumeSetting umsIntegrationConsumeSetting0 = confirmOrderResult0.getIntegrationConsumeSetting();
      
      //Test Result Assert
      assertNull(umsIntegrationConsumeSetting0);
  }

  @Test(timeout = 4000)
  public void test_getMemberIntegration_04()  throws Throwable  {
      //caseID:643b2884b8bc68bcd65904dc0aa45bad
      //CoveredLines: [13, 60]
      //Assert: assertNull(method_result);
      
      ConfirmOrderResult confirmOrderResult0 = new ConfirmOrderResult();
      
      //Call method: getMemberIntegration
      Integer integer0 = confirmOrderResult0.getMemberIntegration();
      
      //Test Result Assert
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test_getMemberReceiveAddressList_05()  throws Throwable  {
      //caseID:4a18dc23b02e6efa0fdb8292a2230747
      //CoveredLines: [13, 36]
      //Assert: assertEquals(0, method_result.size());
      
      ConfirmOrderResult confirmOrderResult0 = new ConfirmOrderResult();
      Stack<UmsMemberReceiveAddress> stack0 = new Stack<UmsMemberReceiveAddress>();
      PrivateAccess.setVariable((Class<?>) ConfirmOrderResult.class, confirmOrderResult0, "memberReceiveAddressList", (Object) stack0);
      
      //Call method: getMemberReceiveAddressList
      List<UmsMemberReceiveAddress> list0 = confirmOrderResult0.getMemberReceiveAddressList();
      
      //Test Result Assert
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test_setCalcAmount_06()  throws Throwable  {
      //caseID:5f48602c08812674e5ba592b7bfcb232
      //CoveredLines: [13, 72, 73]
      //Input_0_ConfirmOrderResult$CalcAmount: {}
      
      ConfirmOrderResult confirmOrderResult0 = new ConfirmOrderResult();
      //mock confirmOrderResult_CalcAmount0
      ConfirmOrderResult.CalcAmount confirmOrderResult_CalcAmount0 = mock(ConfirmOrderResult.CalcAmount.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: setCalcAmount
      confirmOrderResult0.setCalcAmount(confirmOrderResult_CalcAmount0);
      
      //Test Result Assert
      assertNull(confirmOrderResult0.getMemberIntegration());
  }

  @Test(timeout = 4000)
  public void test_setCartPromotionItemList_07()  throws Throwable  {
      //caseID:f629fdd50cae4b8934f44d4633b5422f
      //CoveredLines: [13, 32, 33]
      //Input_0_CartPromotionItem>: arrayList0
      
      ConfirmOrderResult confirmOrderResult0 = new ConfirmOrderResult();
      ArrayList<CartPromotionItem> arrayList0 = new ArrayList<CartPromotionItem>();
      
      //Call method: setCartPromotionItemList
      confirmOrderResult0.setCartPromotionItemList(arrayList0);
      
      //Test Result Assert
      assertTrue(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test_setCouponHistoryDetailList_08()  throws Throwable  {
      //caseID:9beb7b160f6f08aad94be9c04de8c3f7
      //CoveredLines: [13, 48, 49]
      //Input_0_SmsCouponHistoryDetail>: arrayList0
      
      ConfirmOrderResult confirmOrderResult0 = new ConfirmOrderResult();
      ArrayList<SmsCouponHistoryDetail> arrayList0 = new ArrayList<SmsCouponHistoryDetail>();
      
      //Call method: setCouponHistoryDetailList
      confirmOrderResult0.setCouponHistoryDetailList(arrayList0);
      
      //Test Result Assert
      assertTrue(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test_setIntegrationConsumeSetting_09()  throws Throwable  {
      //caseID:560b0564b8d54b494615dc1c538222cc
      //CoveredLines: [13, 56, 57]
      //Input_0_UmsIntegrationConsumeSetting: {}
      
      ConfirmOrderResult confirmOrderResult0 = new ConfirmOrderResult();
      //mock umsIntegrationConsumeSetting0
      UmsIntegrationConsumeSetting umsIntegrationConsumeSetting0 = mock(UmsIntegrationConsumeSetting.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: setIntegrationConsumeSetting
      confirmOrderResult0.setIntegrationConsumeSetting(umsIntegrationConsumeSetting0);
      
      //Test Result Assert
      assertNull(confirmOrderResult0.getMemberIntegration());
  }

  @Test(timeout = 4000)
  public void test_setMemberIntegration_10()  throws Throwable  {
      //caseID:8453be28c9cf02e6da55e7f121ee47e8
      //CoveredLines: [13, 64, 65]
      //Input_0_Integer: 0
      
      ConfirmOrderResult confirmOrderResult0 = new ConfirmOrderResult();
      Integer integer0 = new Integer(0);
      
      //Call method: setMemberIntegration
      confirmOrderResult0.setMemberIntegration(integer0);
      
      //Test Result Assert
      assertEquals(0, (int)confirmOrderResult0.getMemberIntegration());
  }

  @Test(timeout = 4000)
  public void test_setMemberReceiveAddressList_11()  throws Throwable  {
      //caseID:8d63e4106d46792824f32200c419aea9
      //CoveredLines: [13, 40, 41]
      //Input_0_UmsMemberReceiveAddress>: stack0
      
      ConfirmOrderResult confirmOrderResult0 = new ConfirmOrderResult();
      Stack<UmsMemberReceiveAddress> stack0 = new Stack<UmsMemberReceiveAddress>();
      
      //Call method: setMemberReceiveAddressList
      confirmOrderResult0.setMemberReceiveAddressList(stack0);
      
      //Test Result Assert
      assertTrue(stack0.empty());
  }
}
