/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.portal.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.portal.domain.PmsProductCategoryNode;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import org.junit.runner.RunWith;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class PmsProductCategoryNode_SSTest extends PmsProductCategoryNode_SSTest_scaffolding {
// allCoveredLines:[15, 16, 18]

  @Test(timeout = 4000)
  public void test_getChildren_0()  throws Throwable  {
      //caseID:f2e718767304128a0a9b498758a4bbd8
      //CoveredLines: [16, 18]
      //Assert: assertEquals(0, method_result.size());
      
      PmsProductCategoryNode pmsProductCategoryNode0 = new PmsProductCategoryNode();
      Vector<PmsProductCategoryNode> vector0 = new Vector<PmsProductCategoryNode>();
      
      PrivateAccess.setVariable((Class<?>) PmsProductCategoryNode.class, pmsProductCategoryNode0, "children", (Object) vector0);
      
      //Call method: getChildren
      List<PmsProductCategoryNode> list0 = pmsProductCategoryNode0.getChildren();
      
      //Test Result Assert
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test_setChildren_1()  throws Throwable  {
      //caseID:0420dc40629e0f4ed7cc421bf961a5ab
      //CoveredLines: [15, 16]
      //Input_0_List<PmsProductCategoryNode>: arrayList0
      
      PmsProductCategoryNode pmsProductCategoryNode0 = new PmsProductCategoryNode();
      ArrayList<PmsProductCategoryNode> arrayList0 = new ArrayList<PmsProductCategoryNode>();
      
      //Call method: setChildren
      pmsProductCategoryNode0.setChildren(arrayList0);
      
      //Test Result Assert
      assertNull(pmsProductCategoryNode0.getProductCount());
  }
}
